### PR TITLE
[gpuCI] Auto-merge branch-0.8 to branch-0.9

### PR DESCRIPTION
**Pull request by GPUtester**
Auto-merge triggered by push to `branch-0.8` that creates a PR to keep `branch-0.9` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.

### CODE REVIEW

**Comment by GPUtester** [comment]
**FAILURE** - Unable to auto-merge due to conflicts. Manual merge necessary.

**Comment by afender** [comment]
rerun tests

**Comment by afender** [comment]
@raydouglass I think we need you to merge this one. I can't merge PR that skip CI.

**Comment by BradReesWork** [comment]
@raydouglass is this ready to be merged?

**Comment by afender** [comment]
@mike-wendt please advise on how to proceed with this PR as 0.9 release is approaching.

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
Closing as this is replaced by #421

**Pull request closed without merging**
