### PR TITLE
Implement k core

### PR DESCRIPTION
**Pull request by ChuckHastings**
This PR implements the C++ k-core algorithm.

Closes: #2636

### CODE REVIEW

**Comment by ChuckHastings** [comment]
rerun tests

**Review by seunghwak — APPROVED** [review]
LGTM.

**Review by naimnv — APPROVED** [review]

**Review by jnke2016 — APPROVED** [review]
Reviewed and tested. It looks good to me

**Comment by ChuckHastings** [comment]
@gpucibot merge

**Comment by ChuckHastings** [comment]
rerun tests

**Comment by ChuckHastings** [comment]
rerun tests

**Review by jolorunyomi — APPROVED** [review]

**Pull request merged**
