### PR TITLE
`Resultset` and `Dataset` Refactors

### PR DESCRIPTION
**Pull request by nv-rliu**
This PR replaces and is a continuation of #3857 (by @betochimas)

> This PR primarily adds testing for the `Resultset` class, introduced earlier in 23.10. The tests take a similar approach to test_dataset, creating a temporary directory to test downloading all result files. To align `Resultset` and `Dataset`, the setter and getter for each download directory is moved into `DefaultDownloadDir`, so that each class shares an instance of `DefaultDownloadDir` and can be configured independently, although their default locations are still both dependent on the RAPIDS_DATASET_ROOT_DIR_PATH environment variable. The old patterns are present but commented-out, so this change would be breaking. 

This PR also removes the deprecated `experimental.datasets` package due to it being promoted to stable for >=1 release.

### CODE REVIEW

**Review by rlratzel — APPROVED** [review]

**Comment by raydouglass** [comment]
Removing `ops-codeowners` from the required reviews since it doesn't seem there are any file changes that we're responsible for. Feel free to add us back if necessary.

**Comment by nv-rliu** [comment]
Closes https://github.com/rapidsai/graph_dl/issues/297

**Pull request merged**
