### PR TITLE
Add a new notebook for SNMG benchmark runs

### PR DESCRIPTION
**Pull request by naimnv**
This PR adds new notebook for SNMG benchmark runs. It
- [x]  simplifies bookkeeping and data presentation. 
- [x]  update each cugraph function wrappers to handle both SG and MG calls depending on a flag. The object is to have a common set of function wrappers for SG, SNMG and MNMG and put them in a common module to avoid duplication.

### CODE REVIEW

**Review by acostadon — APPROVED** [review]
Looks great to me. 
just need to add your changes to the notebook credits and the copywrite,
I ran it on my workstation up to scale 24 on a 2-GPU workstation and it ran perfectly.
Running on scale 25 now.

**Review by BradReesWork — CHANGES_REQUESTED** [review]
Needs a new Notebook for MG

**Comment by naimnv** [comment]
Sure. We decided not to merge it last week.

**Comment by naimnv** [comment]
@BradReesWork Just to let you know, the updated notbook has `generate_data`  set to `mg=Flase` by default.
`def generate_data(scale, edgefactor=16, mg=False):` 

From correctness point of view, this code will always work.

> This will not work in MG
> gdf = generate_data(v)
> pdf = gdf.to_pandas()

**Comment by naimnv** [comment]
Early next week, I can work this again to make a Notebook for MG.

**Comment by naimnv** [comment]
@BradReesWork @acostadon 
This PR has been updated to include a new notebook for SNMG benchmark runs. I will go over it again, but early review is always valuable.

**Review by BradReesWork — APPROVED** [review]

**Review by jnke2016 — APPROVED** [review]

**Pull request merged**
