### PR TITLE
[REVIEW] Add tolerance support to MG Pagerank and fix kernel launch

### LINKED ISSUE #999: [ENH] Add tolerance support to MG Pagerank
Currently, the MG solver stops after a fixed number of iterations, we should support a tolerance parameter with the same behavior as for single GPU.

### PR DESCRIPTION
**Pull request by afender**
- Closes #999 
- Added tolerance in MG PR
- Removed error throwing when not reaching tolerance in both MG and SG. The solver now exits when the first one between max_iter and tolerance is reached.
- Fixed cuda launch bounds (so that we can accept this from the device properties/handle and not limit it with the old #define)
- The MG pagerank backend returns the number of iterations to the cpp API driver

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by Iroy30** [comment]
CI fails will be fixed with #1008

**Comment by afender** [comment]
> LGTM. Maybe we need to set the same defaults for tolerance and max_iter on both python and C++ level to avoid confusion.
> Also, there's the float/double discrepancy for tolerance and alpha, and int32/64 for max_iter
> These can be fixed in a separate PR as well.

@Iroy30 c79712b added
- 64b types for it/tol as this is what we wrapped.
- python default parameters for C++

**Pull request merged**
