### PR TITLE
Replace clock_gettime with std::chrono::steady_clock

### PR DESCRIPTION
**Pull request by seunghwak**
* Replace clock_gettime in HighResTimer with std::chrono::steady_clock in high_res_timer.hpp
* Move high_res_timer.hpp from src/utilities to include/cugraph/utilities
* Replace HighResClock (tests/utilities/high_res_clock.h) with HighResTimer

### CODE REVIEW

**Comment by seunghwak** [comment]
rerun tests

**Review by ChuckHastings — APPROVED** [review]

**Comment by seunghwak** [comment]
rerun tests

**Comment by seunghwak** [comment]
@jnke2016 This should fix the bug you're facing. Let me know if this doesn't.

```
  if (symmetrized_srcs.size() != org_srcs.size()) {
    return false;
  }
```
https://github.com/rapidsai/cugraph/pull/3055/files#diff-a8d124288865f004d17ae433f23d7bdccb599e31216b95aceb1bdde92f27ebffR86-R89

**Review by naimnv — APPROVED** [review]

**Review by naimnv — APPROVED** [review]

**Comment by rlratzel** [comment]
rerun tests

reason: merged https://github.com/rapidsai/cugraph/pull/3066 which should fix CI errors

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
