### PR TITLE
[REVIEW] Upgrade `dask` and `distributed`

### PR DESCRIPTION
**Pull request by galipremsagar**
This PR upgrades `dask` & `distributed` min versions to be inline with: https://github.com/rapidsai/cudf/pull/10182/

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
