### PR TITLE
[Review] Adding CUDA architecture code for sm80 and aarch64

### PR DESCRIPTION
**Pull request by JasonAtNvidia**
Modified CMakeLists.txt to check for CUDA version and build appropriate gencodes, including those of aarch64 architectures

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Review by BradReesWork — APPROVED** [review]

**Review by afender — APPROVED** [review]

**Comment by afender** [comment]
okay to test

**Comment by afender** [comment]
rerun tests

**Comment by afender** [comment]
okay to test

**Comment by afender** [comment]
@BradReesWork it seems you'll need to authorize testing. I can't do it apparently

**Comment by BradReesWork** [comment]
ok to test

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by BradReesWork** [comment]
@JasonAtNvidia All PR need to include an updated CHANGELOG

**Comment by JasonAtNvidia** [comment]
rerun tests

**Comment by afender** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by afender** [comment]
@JasonAtNvidia, seems like the arch doesn't get set for cuda11:

```
CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
 CUDA_ARCHITECTURES is empty for target "cugraph".
```

**Comment by afender** [comment]
Well for other cuda versions too now... except they didn't crash

**Comment by JasonAtNvidia** [comment]
I will fix this shortly, need to find out why even 60 didn't get set.

**Comment by afender** [comment]
I added a fix tentative. Let's see how it goes.

**Comment by JasonAtNvidia** [comment]
rerun tests

**Comment by afender** [comment]
Status :

Gunrock
https://github.com/rapidsai/cugunrock/pull/3 (need @Bradley Rees to review/merge)
https://github.com/gunrock/gunrock/issues/800 (contribute back to Gunrock tracker)

cuhornet (merged, make sure you get the latest) :
https://github.com/rapidsai/cuhornet/pull/47 (code)
https://github.com/rapidsai/cuhornet/pull/46 (infra)

cugraph
https://github.com/rapidsai/cugraph/pull/1184 (updates tags, blocked by cugunrock PR)
https://github.com/rapidsai/cugraph/pull/1156 (rerun CI and merge once everything else is merged)

**Comment by afender** [comment]
rerun tests

**Comment by afender** [comment]
gunrock is trying to build with arch 80 in Cuda 10, while I think we should only do so for cuda 11

**Comment by afender** [comment]
rerun tests

**Review by afender — APPROVED** [review]

**Comment by bradley** [comment]
been watching this PR too (due to the `@bradley`) good work yall excited to see this go out

**Review by BradReesWork — APPROVED** [review]

**Pull request merged**
