### PR TITLE
Reorganized docs and environment files

### PR DESCRIPTION
**Pull request by BradReesWork**
* reorganized docs so that information is under ./docs/cugraph  that better matches the rest of rapids
* Updated yml files 
* removed unneeded packages in the yml files
* drop old notebook
* marked FA2 notebook as skip

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]
Approving `ops-codeowner` file changes.

Quick comment though. Since we'll be deprecating `10.x` in the `0.19` release ([link](https://docs.rapids.ai/notices/rsn0005/)), you could consider removing the `10.x` yaml files from the `0.20` branch altogether.

**Comment by BradReesWork** [comment]
> Approving `ops-codeowner` file changes.
> 
> Quick comment though. Since we'll be deprecating `10.x` in the `0.19` release ([link](https://docs.rapids.ai/notices/rsn0005/)), you could consider removing the `10.x` yaml files from the `0.20` branch altogether.

I was going to wait until 0.21 to drop those - just in cases we need to revert :-)

**Review by rlratzel — APPROVED** [review]

**Comment by BradReesWork** [comment]
@gpucibot merge

**Comment by ajschmidt8** [comment]
rerun tests

**Review by Iroy30 — APPROVED** [review]
Looks good

**Pull request merged**
