### PR TITLE
remove all algorithms from cython.cu

### LINKED ISSUE #2498: MNMG WCC - Remove from cython.cu
Remove WCC functionality from cython.cu.

Depends on #2496

### PR DESCRIPTION
**Pull request by ChuckHastings**
Should unblock #2834 

This removes all of the algorithms from `cython.cu`.

Closes #2498 

Marked as breaking since we remove some old python bindings, they should no longer be used.

### CODE REVIEW

**Review by seunghwak — APPROVED** [review]
LGTM, thanks for this great effort!

And just a side question, we still need to perform shuffle and renumber through cython?

**Comment by ChuckHastings** [comment]
> And just a side question, we still need to perform shuffle and renumber through cython?

Joseph is working on the python changes for that, they aren't merged yet.

**Review by jnke2016 — APPROVED** [review]
Looks good to me.

**Comment by ChuckHastings** [comment]
@gpucibot merge

**Review by BradReesWork — APPROVED** [review]

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
