### PR TITLE
[skip gpuci] Update dgl-cuda conda installation instructions

### PR DESCRIPTION
**Pull request by VibhuJawa**
Update dgl-cuda conda installation instructions 

Closes: https://github.com/rapidsai/cugraph/issues/2969

### CODE REVIEW

**Review by BradReesWork — APPROVED** [review]

**Comment by VibhuJawa** [comment]
rerun tests

Reason: Unrelated conda failures

**Review by jnke2016 — APPROVED** [review]

**Comment by BradReesWork** [comment]
rerun tests

**Comment by VibhuJawa** [comment]
rerun tests

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
