### PR TITLE
replace `ccache` with `sccache`

### PR DESCRIPTION
**Pull request by AyodeAwe**
This PR replaces ccache with sccache.

### CODE REVIEW

**Comment by ajschmidt8** [comment]
pre-cache C++ build time ([log link](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cugraph/job/prb/job/cugraph-cpu-cuda-build/1566/CUDA=11.5/consoleText)): 1:47:12.4

image

**Comment by ajschmidt8** [comment]
post-cache C++ build time ([log link](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cugraph/job/prb/job/cugraph-cpu-cuda-build/1568/CUDA=11.5/consoleText)): 0:02:18.3

image

**Comment by AyodeAwe** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
PR is ready for review, but we'll wait to merge until all the other PRs are confirmed working as well.

**Review by ajschmidt8 — CHANGES_REQUESTED** [review]
We'll need to update the recipe below as well.

- https://github.com/rapidsai/cugraph/blob/branch-22.04/conda/recipes/libcugraph_etl/meta.yaml

**Review by ajschmidt8 — APPROVED** [review]

**Comment by ajschmidt8** [comment]
@gpucibot merge

**Pull request merged**
