### PR TITLE
Update cugraph-pyg models for PyG 2.5

### PR DESCRIPTION
**Pull request by tingyu66**
- Support [`torch_geometric.EdgeIndex`](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.edge_index.EdgeIndex.html) in models.
- Drop support for PyG < 2.5

Breaking changes: 
The `csc` argument in `model.forward()` has been renamed to `edge_index` to align with upstream models. For now, users can still pass in CSC tuples (generated from `to_csc` call) as `edge_index`.

### CODE REVIEW

**Comment by alexbarghi-nv** [comment]
Make sure you update the PyG version in `dependencies.yaml` too.

**Comment by tingyu66** [comment]
> Make sure you update the PyG version in `dependencies.yaml` too.

Updated now, though `cugraph_pyg_dev` not being used under the current setup.

**Comment by tingyu66** [comment]
> Sorry I messed this PR up. I'll approve once the unintentional changes I made are reverted.

@alexbarghi-nv  The diff has been fixed, feel free to take a look.

**Review by alexbarghi-nv — APPROVED** [review]
👍

**Review by AyodeAwe — APPROVED** [review]

**Pull request merged**
