### PR TITLE
[REVIEW] Upgrade `clang` to `11.1.0`

### PR DESCRIPTION
**Pull request by galipremsagar**
This upgrade is required to be in-line with: rapidsai/cudf#9716

Depends on: rapidsai/integration#390

### CODE REVIEW

**Review by raydouglass — APPROVED** [review]

**Review by BradReesWork — APPROVED** [review]

**Comment by BradReesWork** [comment]
@galipremsagar there is a style check error

**Comment by galipremsagar** [comment]
> @galipremsagar there is a style check error

Yes, we need the new images to be build since the integration changes just got merged: https://github.com/rapidsai/integration/pull/390

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by rlratzel** [comment]
@gpucibot merge

**Pull request merged**
