### PR TITLE
[REVIEW] Fix error in Graph.edges(), update cuDF rename() calls

### PR DESCRIPTION
**Pull request by trxcllnt**
* Fixes places that are breaking from changes in cuDF's `DataFrame.rename()` method
* Ensures columns are named `src, dst` in `Graph.view_edge_list()` when graph was created via `renumber_from_cudf`. Presently they're named `0_x` and `0_y`, causing `Graph.edges()` to throw an error

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by trxcllnt** [comment]
I see these changes are also in https://github.com/rapidsai/cugraph/pull/974. The main difference is I'm also passing `copy=False` to `df.rename()` since it's safe to avoid copying in cuGraph tests/internals.

**Comment by afender** [comment]
rerun tests

**Comment by trxcllnt** [comment]
I'm not sure what the `codecov/patch` CI check is verifying?

**Pull request merged**
