### PR TITLE
[review] Updated versions in conda envs

### PR DESCRIPTION
**Pull request by afender**

### CODE REVIEW

**Comment by afender** [comment]
@raydouglass it seems that cudf 0.6 conflicts with jenkins env. The PR works fine when creating the env from scratch.

**Comment by afender** [comment]
This may not be related to this PR actually. I noticed the same Jenkins error in other PR on Jenkins today.

**Comment by raydouglass** [comment]
rerun tests

**Comment by afender** [comment]
@raydouglass, did it really rerun after your fix?  I still see :
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - cudf=0.6
```

**Pull request merged**
