### PR TITLE
[REVIEW] Run all tests in gpu test script

### PR DESCRIPTION
**Pull request by raydouglass**
Simply adds downloading the test datasets and looping over the gtests and running each one.

I've adapted this from @rlratzel's container test script.

### CODE REVIEW

**Comment by afender** [comment]
rerun tests

**Comment by afender** [comment]
@jwyles it seems like find matches tests are still failing. I can't merge this PR without find matches being fixed first.

**Comment by afender** [comment]
@BradReesWork, test won't pass until #570 is merged

**Comment by BradReesWork** [comment]
I though that FindMatches was dropped from the release?  If so, let's skip the FindMatches test

**Comment by afender** [comment]
rerun tests

**Comment by afender** [comment]
Yep, rerunning tests now that FindMatches is dropped in the 0.11 branch.

**Comment by BradReesWork** [comment]
rerun tests

**Pull request merged**
