### PR TITLE
Update the neighbor intersection primitive to support edge masking.

### PR DESCRIPTION
**Pull request by seunghwak**
This PR updates the detail::nbr_intersection() primitive and the per_v_pair_transform_dst_nbr_intersection primitive (which calls the detail::nbr_intersection primitive) to work with edge masking (graph_view_t object with attached edge mask). Several utility functions are updated to support edge masking as well to support primitive updates and testing.

This PR is necessary to implement K-truss with the cuGraph C++ primitives. See https://github.com/rapidsai/cugraph/issues/3446#issuecomment-1499649664 for additional details.

### CODE REVIEW

**Comment by seunghwak** [comment]
This PR is now ready for review.

**Review by ChuckHastings — APPROVED** [review]

**Review by naimnv — APPROVED** [review]

**Review by jnke2016 — APPROVED** [review]
Looks good to me

**Pull request merged**
