### PR TITLE
force atlas notebook changes to run in cugraph 23.08 container.

### LINKED ISSUE #3653: Fix Force Atlas 2 notebook error
Notebook throws an error:
```
WARNING:param.dynamic_operation: Callable raised "AttributeError("module 'numpy' has no attribute 'warnings'")".
Invoked as dynamic_operation(height=400, scale=1.0, width=400, x_range=None, y_range=None)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/opt/conda/envs/rapids/lib/python3.10/site-packages/IPython/core/formatters.py in __call__(self, obj, include, exclude)
    968 
    969             if method is not None:
--> 970                 return method(include=include, exclude=exclude)
    971             return None
.
.
.
/opt/conda/envs/rapids/lib/python3.10/site-packages/numpy/__init__.py in __getattr__(attr)
    318             return Tester
    319 
--> 320         raise AttributeError("module {!r} has no attribute "
    321                              "{!r}".format(__name__, attr))
    322 

AttributeError: module 'numpy' has no attribute 'warnings'
```
Error is caused by use of removed calls in numpy. 

- [ ] Add in environment variable for Datasets directory in container environment
- [ ] Add code to fetch dataset if necessary
- [ ] remove call to library using outdated numpy api and annotate why this is done in the notebook
- [ ] open a ticket in the erroring library and insert link to error in notebook
- [ ]  verify that notebook works seamlessly in the rapids nightly container while including any necessary instructions for running in conda.

### PR DESCRIPTION
**Pull request by acostadon**
changes to allow for libary dependence on no longer supported numpy functions.
Also addresses notebook's need for cuxfilter.

resolves #3653

### CODE REVIEW

**Comment by BradReesWork** [comment]
You need either a note that this notebook only running in the rapids docker container or provide a list of how to install the needed packages

**Comment by rlratzel** [comment]
## force atlas notebook changes to run in cugraph 23.08 container

Which container (RAPIDS runtime, DLFW, etc.)?  Can that be mentioned somewhere?

**Comment by rlratzel** [comment]
I tried to review but GH gave this message:
"296 additions, 30 deletions not shown because the diff is too large. Please use a local Git client to view these changes. "

I'm curious why the diff was so large and how many changes were required to get this NB to run in the container environment you're using.  Can you maybe update this PR description to summarize the changes? (looks like the description needs updating anyway since it mentions filing an issue, and has a "resolves" for itself :) )

**Review by BradReesWork — APPROVED** [review]

**Pull request merged**
