### PR TITLE
CuGraph compatibility fixes

### PR DESCRIPTION
**Pull request by brandon-b-miller**
This PR contains two changes.
- A change that defers to `numpy.asarray` to process array objects that `cugraph` consumes
- An update from using `unique` to use `drop_duplicates` in `simpleGraph.py`, which always always returns a Series to preserve pandas compatibility.

### CODE REVIEW

**Review by rlratzel — APPROVED** [review]
Thanks!

**Comment by brandon-b-miller** [comment]
failing just a few tests here - looking into it.

**Comment by brandon-b-miller** [comment]
Could someone with permission rerun the one failing job? I think the failure could be transient
```
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
```

**Pull request merged**
