### PR TITLE
[WIP] BSP BFS - fix API and test

### LINKED ISSUE #605: [FEA] BSP BFS - API and Test
BSP BFS should accept a Graph type

Tests need to also validate vertex and distance

Add option to return all vertices and sort results

### PR DESCRIPTION
**Pull request by BradReesWork**
Fixing the API to accept 'Graph'  and fixing teh tests so that they pass

closes #605

### CODE REVIEW

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by Iroy30** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Pull request closed without merging**
