### PR TITLE
Updated python and cuda in scripts

### PR DESCRIPTION
**Pull request by jolorunyomi**
PYTHON variables and CUDA variables updated

### CODE REVIEW

**Comment by rlratzel** [comment]
What happened to #1795 ? It looks like that one was closed without merging, but has a slightly different set of files with similar changes.  If they're related, can you describe how they differ, why the old one was closed, etc.? Also, can you update the description with why the variables are changing and if developers need to update anything in their environment?

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
@jolorunyomi the PR is not passing CI

**Comment by jolorunyomi** [comment]
> What happened to #1795 ? It looks like that one was closed without merging, but has a slightly different set of files with similar changes. If they're related, can you describe how they differ, why the old one was closed, etc.? Also, can you update the description with why the variables are changing and if developers need to update anything in their environment?

The first PR had unrelated automated changes and so the work had to be re-done.

**Comment by BradReesWork** [comment]
rerun tests

**Pull request closed without merging**
