### PR TITLE
Add parameter checks to BFS and SSSP in C API

### PR DESCRIPTION
**Pull request by ChuckHastings**
MG testing resulted in discovering an assumption in the C API about types that needs to be validated.  Added checks to BFS and SSSP so that the type checks will be done right away before trying to interpret the data incorrectly.

Won't pass until #2847 is addressed

### CODE REVIEW

**Review by seunghwak — APPROVED** [review]

**Review by jnke2016 — APPROVED** [review]

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by ChuckHastings** [comment]
rerun tests

**Comment by ChuckHastings** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by ChuckHastings** [comment]
rerun tests

**Comment by ChuckHastings** [comment]
rerun tests

**Comment by rlratzel** [comment]
This is a good change but can there be an updated test to cover this change?

**Comment by BradReesWork** [comment]
rerun tests

**Review by rlratzel — APPROVED** [review]

**Comment by ChuckHastings** [comment]
@gpucibot merge

**Pull request merged**
