### PR TITLE
Testing RAFT changes hide implementation details for communicator

### PR DESCRIPTION
**Pull request by cjnolet**

### CODE REVIEW

**Comment by BradReesWork** [comment]
rerun tests

**Comment by cjnolet** [comment]
rerun tests

**Comment by cjnolet** [comment]
rerun tests

**Comment by cjnolet** [comment]
@robertmaynard, it looks like we're getting some `cuco` compile errors in CI here:

```bash
11:42:45 ../include/cugraph/prims/copy_v_transform_reduce_key_aggregated_out_nbr.cuh(293): error: no instance of function template "cuco::static_map<Key, Value, Scope, Allocator>::insert [with Key=int32_t, Value=float, Scope=cuda::std::__4::__detail::thread_scope_device, Allocator=rmm::mr::stream_allocator_adaptor<rmm::mr::polymorphic_allocator<char>>]" matches the argument list
```

I recall the cuco git hash was updated twice yesterday, once by @seunghwak and in https://github.com/rapidsai/raft/pull/446. Can you confirm it's currently at the correct tag?

**Comment by cjnolet** [comment]
rerun tests

**Comment by cjnolet** [comment]
@robertmaynard, @seunghwak disregard, I think my branch was out of sync.

**Comment by cjnolet** [comment]
rerun tests

**Comment by cjnolet** [comment]
rerun tests

**Comment by cjnolet** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
Removing `ops-codeowners` from the required reviews since it doesn't seem there are any file changes that we're responsible for. Feel free to add us back if necessary.

**Comment by cjnolet** [comment]
rerun tests

**Comment by cjnolet** [comment]
rerun tests

**Review by BradReesWork — APPROVED** [review]

**Comment by cjnolet** [comment]
This has been merged on the raft side. Closing

**Pull request closed without merging**
