### PR TITLE
Add package to the list of dependencies

### LINKED ISSUE #2857: [BUG]: Pytest no longer lists the package py as a dependency
### Version

22.12

### Which installation method(s) does this occur on?

Conda

### Describe the bug.

The package `py` which was a pytest dependency is no longer with pytest 7.2.

### Minimum reproducible example

```shell
Run any MG cuGraph test.
```

### Relevant log output

```shell
INTERNALERROR> Traceback (most recent call last):
[6](https://mg-test-results.s3.us-east-2.amazonaws.com/cugraph/2022-10-27_09:30:02_UTC/tests/test_mg_batch_betweenness_centrality/2-GPUs/pytest_output_log.html#6): INTERNALERROR>   File "/gpfs/fs1/projects/sw_rapids/users/jnke/miniconda3/envs/cugraph_test/lib/python3.9/site-packages/_pytest/main.py", line 266, in wrap_session
[7](https://mg-test-results.s3.us-east-2.amazonaws.com/cugraph/2022-10-27_09:30:02_UTC/tests/test_mg_batch_betweenness_centrality/2-GPUs/pytest_output_log.html#7): INTERNALERROR>     config._do_configure()
[8](https://mg-test-results.s3.us-east-2.amazonaws.com/cugraph/2022-10-27_09:30:02_UTC/tests/test_mg_batch_betweenness_centrality/2-GPUs/pytest_output_log.html#8): INTERNALERROR>   File "/gpfs/fs1/projects/sw_rapids/users/jnke/miniconda3/envs/cugraph_test/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1037, in _do_configure
[9](https://mg-test-results.s3.us-east-2.amazonaws.com/cugraph/2022-10-27_09:30:02_UTC/tests/test_mg_batch_betweenness_centrality/2-GPUs/pytest_output_log.html#9): INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
[10](https://mg-test-results.s3.us-east-2.amazonaws.com/cugraph/2022-10-27_09:30:02_UTC/tests/test_mg_batch_betweenness_centrality/2-GPUs/pytest_output_log.html#10): INTERNALERROR>   File "/gpfs/fs1/projects/sw_rapids/users/jnke/miniconda3/envs/cugraph_test/lib/python3.9/site-packages/pluggy/_hooks.py", line 277, in call_historic
[11](https://mg-test-results.s3.us-east-2.amazonaws.com/cugraph/2022-10-27_09:30:02_UTC/tests/test_mg_batch_betweenness_centrality/2-GPUs/pytest_output_log.html#11): INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
[12](https://mg-test-results.s3.us-east-2.amazonaws.com/cugraph/2022-10-27_09:30:02_UTC/tests/test_mg_batch_betweenness_centrality/2-GPUs/pytest_output_log.html#12): INTERNALERROR>   File "/gpfs/fs1/projects/sw_rapids/users/jnke/miniconda3/envs/cugraph_test/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
[13](https://mg-test-results.s3.us-east-2.amazonaws.com/cugraph/2022-10-27_09:30:02_UTC/tests/test_mg_batch_betweenness_centrality/2-GPUs/pytest_output_log.html#13): INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
[14](https://mg-test-results.s3.us-east-2.amazonaws.com/cugraph/2022-10-27_09:30:02_UTC/tests/test_mg_batch_betweenness_centrality/2-GPUs/pytest_output_log.html#14): INTERNALERROR>   File "/gpfs/fs1/projects/sw_rapids/users/jnke/miniconda3/envs/cugraph_test/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
[15](https://mg-test-results.s3.us-east-2.amazonaws.com/cugraph/2022-10-27_09:30:02_UTC/tests/test_mg_batch_betweenness_centrality/2-GPUs/pytest_output_log.html#15): INTERNALERROR>     return outcome.get_result()
[16](https://mg-test-results.s3.us-east-2.amazonaws.com/cugraph/2022-10-27_09:30:02_UTC/tests/test_mg_batch_betweenness_centrality/2-GPUs/pytest_output_log.html#16): INTERNALERROR>   File "/gpfs/fs1/projects/sw_rapids/users/jnke/miniconda3/envs/cugraph_test/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
[17](https://mg-test-results.s3.us-east-2.amazonaws.com/cugraph/2022-10-27_09:30:02_UTC/tests/test_mg_batch_betweenness_centrality/2-GPUs/pytest_output_log.html#17): INTERNALERROR>     raise ex[1].with_traceback(ex[2])
[18](https://mg-test-results.s3.us-east-2.amazonaws.com/cugraph/2022-10-27_09:30:02_UTC/tests/test_mg_batch_betweenness_centrality/2-GPUs/pytest_output_log.html#18): INTERNALERROR>   File "/gpfs/fs1/projects/sw_rapids/users/jnke/miniconda3/envs/cugraph_test/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
[19](https://mg-test-results.s3.us-east-2.amazonaws.com/cugraph/2022-10-27_09:30:02_UTC/tests/test_mg_batch_betweenness_centrality/2-GPUs/pytest_output_log.html#19): INTERNALERROR>     res = hook_impl.function(*args)
[20](https://mg-test-results.s3.us-east-2.amazonaws.com/cugraph/2022-10-27_09:30:02_UTC/tests/test_mg_batch_betweenness_centrality/2-GPUs/pytest_output_log.html#20): INTERNALERROR>   File "/gpfs/fs1/projects/sw_rapids/users/jnke/miniconda3/envs/cugraph_test/lib/python3.9/site-packages/pytest_benchmark/plugin.py", line 442, in pytest_configure
[21](https://mg-test-results.s3.us-east-2.amazonaws.com/cugraph/2022-10-27_09:30:02_UTC/tests/test_mg_batch_betweenness_centrality/2-GPUs/pytest_output_log.html#21): INTERNALERROR>     bs = config._benchmarksession = BenchmarkSession(config)
[22](https://mg-test-results.s3.us-east-2.amazonaws.com/cugraph/2022-10-27_09:30:02_UTC/tests/test_mg_batch_betweenness_centrality/2-GPUs/pytest_output_log.html#22): INTERNALERROR>   File "/gpfs/fs1/projects/sw_rapids/users/jnke/miniconda3/envs/cugraph_test/lib/python3.9/site-packages/pytest_benchmark/session.py", line 32, in __init__
[23](https://mg-test-results.s3.us-east-2.amazonaws.com/cugraph/2022-10-27_09:30:02_UTC/tests/test_mg_batch_betweenness_centrality/2-GPUs/pytest_output_log.html#23): INTERNALERROR>     self.logger = Logger(self.verbose, config)
[24](https://mg-test-results.s3.us-east-2.amazonaws.com/cugraph/2022-10-27_09:30:02_UTC/tests/test_mg_batch_betweenness_centrality/2-GPUs/pytest_output_log.html#24): INTERNALERROR>   File "/gpfs/fs1/projects/sw_rapids/users/jnke/miniconda3/envs/cugraph_test/lib/python3.9/site-packages/pytest_benchmark/logger.py", line 18, in __init__
[25](https://mg-test-results.s3.us-east-2.amazonaws.com/cugraph/2022-10-27_09:30:02_UTC/tests/test_mg_batch_betweenness_centrality/2-GPUs/pytest_output_log.html#25): INTERNALERROR>     self.term = py.io.TerminalWriter(file=sys.stderr)
[26](https://mg-test-results.s3.us-east-2.amazonaws.com/cugraph/2022-10-27_09:30:02_UTC/tests/test_mg_batch_betweenness_centrality/2-GPUs/pytest_output_log.html#26): INTERNALERROR> AttributeError: module 'py' has no attribute 'io'
```
```


### Environment details

_No response_

### Other/Misc.

_No response_

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

### LINKED ISSUE #2881: [BUG]: Change in the external use of cuDF 'Buffer'
### Version

22.12

### Which installation method(s) does this occur on?

Docker, Conda, Source

### Describe the bug.

In an effort to enable a spillable sub-class of Buffer, a [breaking change](https://github.com/rapidsai/cudf/pull/12009) was introduced by cuDF that altered the external use of `Buffer` . In fact, the "constructor-kwargs" had been removed leading to the error provided in the log output section.

### Minimum reproducible example

```shell
Run the python BFS tests.
```

### Relevant log output

```shell
tests/test_bfs.py:332: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_bfs.py:264: in get_cu_graph_nx_graph_and_params
    G = dataset.get_graph(create_using=cugraph.Graph(directed=directed))
/opt/conda/envs/rapids/lib/python3.9/site-packages/cugraph-22.12.0a0+93.ge93f5ba5.dirty-py3.9-linux-x86_64.egg/cugraph/experimental/datasets/dataset.py:174: in get_graph
    self._graph.from_cudf_edgelist(
/opt/conda/envs/rapids/lib/python3.9/site-packages/cugraph-22.12.0a0+93.ge93f5ba5.dirty-py3.9-linux-x86_64.egg/cugraph/structure/graph_classes.py:166: in from_cudf_edgelist
    self._Impl._simpleGraphImpl__from_edgelist(
/opt/conda/envs/rapids/lib/python3.9/site-packages/cugraph-22.12.0a0+93.ge93f5ba5.dirty-py3.9-linux-x86_64.egg/cugraph/structure/graph_implementation/simpleGraph.py:186: in __from_edgelist
    elist, renumber_map = NumberMap.renumber(
/opt/conda/envs/rapids/lib/python3.9/site-packages/cugraph-22.12.0a0+93.ge93f5ba5.dirty-py3.9-linux-x86_64.egg/cugraph/structure/number_map.py:717: in renumber
    return NumberMap.renumber_and_segment(
/opt/conda/envs/rapids/lib/python3.9/site-packages/cugraph-22.12.0a0+93.ge93f5ba5.dirty-py3.9-linux-x86_64.egg/cugraph/structure/number_map.py:679: in renumber_and_segment
    renumbering_map, segment_offsets, renumbered_df = c_renumber.renumber(
renumber_wrapper.pyx:215: in cugraph.structure.renumber_wrapper.renumber
    ???
graph_primtypes.pyx:52: in cugraph.structure.graph_primtypes.move_device_buffer_to_series
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   TypeError: __init__() takes 1 positional argument but 2 were given

graph_primtypes.pyx:37: TypeError
```

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

### PR DESCRIPTION
**Pull request by jnke2016**
A breaking `pytest `change removed the `py` package from its list of dependencies causing the SG/MG tests to fail.
This PR  adds the package to our list of dependencies. 
In addition to the above, this PR also:
1. Reduces the value of the `fanout_vals` when testing `uniform_neighbor_sampling`
2. Updates the ownership transfer of `device_buffer_unique_ptr` to cuDF buffer through the call `as_buffer()`

closes #2857 
closes #2881

### CODE REVIEW

**Comment by jnke2016** [comment]
rerun tests

**Review by rlratzel — APPROVED** [review]

**Comment by msadang** [comment]
rerun tests

**Comment by ChuckHastings** [comment]
rerun tests

**Review by rlratzel — APPROVED** [review]

**Review by msadang — APPROVED** [review]
py and range changes look good.

**Comment by BradReesWork** [comment]
@gpucibot merge

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
