### PR TITLE
[REVIEW] Explicitly skip raft test folder for pytest 6.0.0 [skip-ci]

### PR DESCRIPTION
**Pull request by dantegd**
Similar to https://github.com/rapidsai/cuml/pull/2619, there is a very high chance CI in cuGraph will run into the same issue as cuML now with pytest 6.0.0. 

The PR also changes `py.test` (which is the old school invocation) to the current `pytest` command.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by dantegd** [comment]
@afender I would leave both just to keep CI unblocked, then we can look whether the conftest/skip flag are both needed in a follow up, what do you think?

**Comment by dantegd** [comment]
rerun tests

**Comment by dantegd** [comment]
there seems to be an (unrelated) test failing in cuda 10.1 CI: 
```
FAILED cugraph/tests/test_balanced_cut.py::test_edge_cut_clustering[2-../datasets/dolphins.csv]
```
is that a known issue?

**Comment by dantegd** [comment]
rerun tests

**Pull request merged**
