### PR TITLE
[REVIEW] Use RAFT CUDA utilities

### PR DESCRIPTION
**Pull request by seunghwak**
Close RAFT issue https://github.com/rapidsai/raft/issues/24 with https://github.com/rapidsai/raft/pull/37

Cannot be merged before https://github.com/rapidsai/raft/pull/37

Remove CUDA utility files from cuGraph, use RAFT ones instead.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by BradReesWork** [comment]
rerun test

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by seunghwak** [comment]
rerun tests

**Pull request merged**
