### PR TITLE
[REVIEW] Fixed CUDA 11 Pagerank crash

### PR DESCRIPTION
**Pull request by aschaffer**
Replaced CUB's `CsrMV` with `raft`'s SpMV in CUDA 11. This fixes the problem.

CUB is still in use in 10.2 and below.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by aschaffer** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Pull request merged**
