### PR TITLE
Fix Edge case in Bulk Sampler

### PR DESCRIPTION
**Pull request by VibhuJawa**
This PR fixes an edge case which leads to infinite recursion. 

- [x] Added Tests

CC: @alexbarghi-nv

### CODE REVIEW

**Review by alexbarghi-nv — APPROVED** [review]
Ok, this looks good.

**Comment by alexbarghi-nv** [comment]
@VibhuJawa can I mark this as ready and merge it?

**Comment by VibhuJawa** [comment]
> @VibhuJawa can I mark this as ready and merge it?

Yup, now you can. Added a test . Feel free to merge it now.

**Pull request merged**
