### PR TITLE
[REVIEW] Patch Thrust to workaround CUDA_CUB_RET_IF_FAIL macro clearing CUDA errors

### PR DESCRIPTION
**Pull request by kkraus14**
Copied from https://github.com/rapidsai/cudf/pull/6098

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by raydouglass** [comment]
rerun tests

**Comment by rlratzel** [comment]
rerun tests

reason: CondaHTTPError

**Comment by kkraus14** [comment]
Please don't rerun things, it's 404ing being libcudf is being rebuilt with the patched thrust currently.

**Pull request merged**
