### PR TITLE
Require `ucx-proc=*=gpu`

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Review by raydouglass — APPROVED** [review]

**Review by dillon-cullinan — CHANGES_REQUESTED** [review]
Need changes here, no?

https://github.com/rapidsai/cugraph/blob/branch-0.17/ci/gpu/build.sh

**Comment by jakirkham** [comment]
@dillon-cullinan, can you please recheck? Should be in the latest commit.

**Review by pentschev — APPROVED** [review]
LGTM, thanks @jakirkham .

**Comment by jakirkham** [comment]
Fixed a few more CI files. Think that is it.

**Review by dillon-cullinan — APPROVED** [review]

**Pull request merged**
