### PR TITLE
Replacing markdown issue templates with yml forms

### PR DESCRIPTION
**Pull request by jarmak-nv**
This PR replaces the existing markdown issue templates with [form-based YML templates](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/). They provide a more interactive experience and can require certain fields be filled out prior to issue submission.

### CODE REVIEW

**Comment by jarmak-nv** [comment]
To see how these look in action, and if anything should be changed for cuGraph, check out the Morpheus implementation [here](https://github.com/nv-morpheus/Morpheus/issues/new/choose)

**Review by BradReesWork — APPROVED** [review]

**Comment by BradReesWork** [comment]
Looks good and I like the new form style

**Review by rlratzel — APPROVED** [review]
LGTM

**Review by sean-frye — APPROVED** [review]
LGTM

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
