### PR TITLE
[REVIEW] Update README

### PR DESCRIPTION
**Pull request by ChuckHastings**
Update links to stable reference.

Addresses #1112 

Doesn't do anything about the Transition Guide comment in that issue (yet).

### CODE REVIEW

**Comment by BradReesWork** [comment]
@ChuckHastings this was fixed in #1105

**Comment by ChuckHastings** [comment]
> @ChuckHastings this was fixed in #1105

Only partially.  #1105 fixed the main/master edit.  But the link still takes you to cuDF instead of cuGraph

**Comment by BradReesWork** [comment]
replaced by PR #1129

**Comment by ChuckHastings** [comment]
Will fix in another PR

**Pull request closed without merging**
