### PR TITLE
Replace deprecated raft headers

### LINKED ISSUE #2840: [FEA] Remove deprecated Raft headers
**Describe the solution you'd like and any additional context**
Some of the code in cugraph is using deprecated headers of Raft which will be removed in a future version of Raft.

---
_For Developers below this line_

  - [] Code passes CI
  - [] Code uses Graph Primitives
  - [x] Code in C++/CUDA layer
  - [] Code in C layer
  - [] Code in pylibcugraph Python layer
  - [] Code in cugraph Python layer
  - [] Documentation
  - [] Test cases at each layer (for MG tests, a note in the PR description indicating the new/existing MG tests were run and passed)

### PR DESCRIPTION
**Pull request by lowener**
Closes #2840 
Linking: https://github.com/rapidsai/raft/issues/555

### CODE REVIEW

**Review by ChuckHastings — APPROVED** [review]

**Comment by lowener** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by lowener** [comment]
rerun tests

**Comment by BradReesWork** [comment]
@lowener merge conflicts

**Comment by lowener** [comment]
rerun tests

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
