### PR TITLE
Updates dependency to latest DGL

### PR DESCRIPTION
**Pull request by rlratzel**
Updates runtime dependency to latest DGL

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]

**Review by VibhuJawa — APPROVED** [review]
LGTM

**Comment by rlratzel** [comment]
rerun tests

reason: CI job was marked as cancelled for some reason

**Comment by ajschmidt8** [comment]
> rerun tests
> 
> reason: CI job was marked as cancelled for some reason

@rlratzel, just a reminder that `rerun tests` doesn't work with GitHub Actions.

See the docs below for more details.

- https://docs.rapids.ai/resources/github-actions/#rerunning-failed-github-actions

Also, this job timed out after 6 hours due to some connectivity issues when performing a conda command.

In the future, we'll be adding some timeout functionality to these conda operations so that they'll automatically be canceled and retried if they don't complete in a certain amount of time.

For now, the only way to resolve this is to rerun the job manually according to the docs above.

**Comment by ajschmidt8** [comment]
I've just rerun the failed job.

**Pull request merged**
