### PR TITLE
[REVIEW] updated to use master version of DASK

### PR DESCRIPTION
**Pull request by BradReesWork**
updated the build script

### CODE REVIEW

**Comment by BradReesWork** [comment]
rerun test

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
Not sure this is needed anymore since the DASK issue was fixed.  But this better aligns with how cuDF loads DASK

**Comment by seunghwak** [comment]
So cuDF plans to keep this change (pip install dask & distributed) or cuDF plans to revert to the previous way as the DASK issue is resolved?

@kkraus14 Do you have any comments on this?

**Comment by kkraus14** [comment]
> So cuDF plans to keep this change (pip install dask & distributed) or cuDF plans to revert to the previous way as the DASK issue is resolved?
> 
> @kkraus14 Do you have any comments on this?

We plan to continue using the `master` version of both dask and distributed. Pushing for those to be used in nightly tests as well.

**Comment by afender** [comment]
I noticed some test errors on gpuCI. This is not expected as the problematic test (`test_hibench_small.py`) has been disabled by @kaatish 's PR and the fix was merged earlier this week (https://github.com/rapidsai/cugraph/pull/477).

@dillon-cullinan / @rlratzel  : It seems that gpuCI picks an older version of the codebase, is there a ci issue?

```
__________ ERROR collecting cugraph/tests/dask/test_hibench_small.py ___________

ImportError while importing test module '/var/lib/jenkins/workspace/gpuCI/cugraph/prb/cugraph-gpu-build_2/python/cugraph/tests/dask/test_hibench_small.py'.

Hint: make sure your test modules/packages have valid Python names.

Traceback:

cugraph/tests/dask/test_hibench_small.py:16: in <module>

    from dask_cuda import LocalCUDACluster

/conda/envs/gdf/lib/python3.6/site-packages/dask_cuda/__init__.py:1: in <module>

    from .local_cuda_cluster import LocalCUDACluster

/conda/envs/gdf/lib/python3.6/site-packages/dask_cuda/local_cuda_cluster.py:7: in <module>

    from distributed.worker import TOTAL_MEMORY

E   ImportError: cannot import name 'TOTAL_MEMORY'
```

**Comment by afender** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Pull request merged**
