### PR TITLE
[REVIEW] write into csv

### PR DESCRIPTION
**Pull request by Iroy30**

### CODE REVIEW

**Comment by afender** [comment]
rerun tests

**Comment by afender** [comment]
Waiting on DGX 2 test before merging

**Comment by Iroy30** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by afender** [comment]
Waiting on :
- csv write chunk size to be set to avoid oom issue on large sizes 
- test_hibench_small.py update

**Comment by afender** [comment]
+ let's try to re-enable dask tests in this PR before we release 0.10

**Comment by Iroy30** [comment]
rerun tests

**Pull request merged**
