### PR TITLE
Changed ci build_docs to just upload the xml so the cugraph-docs can create the docs

### PR DESCRIPTION
**Pull request by acostadon**
… create the docs

### CODE REVIEW

**Review by BradReesWork — CHANGES_REQUESTED** [review]
Lines 31 - 61 should also be redone.  Since cugraph no longer builds the full set of Docs, there is no need to bring in the other external packages

**Review by jameslamb — COMMENTED** [review]
Oh cool, hadn't noticed this PR before! `@` me any time you've addressed other comments and are ready for a `ci-codeowners` review (since I'd been helping over in https://github.com/rapidsai/cugraph-docs/pull/46)

**Comment by AyodeAwe** [comment]
@BradReesWork could you take a second look at this PR?

**Review by BradReesWork — APPROVED** [review]
did you verify that this will actually push the xml file?

**Comment by AyodeAwe** [comment]
> did you verify that this will actually push the xml file?

Confirmed in a previous run shown here: https://github.com/rapidsai/cugraph/actions/runs/12203540777/job/34049336099#step:10:11180

But we'll wait for the docs build in this new run to confirm again anyway.

**Comment by AyodeAwe** [comment]
Looks like the `dgl` package is still needed:

image

https://github.com/rapidsai/cugraph/actions/runs/12261494613/job/34211741255#step:10:9320

**Comment by AyodeAwe** [comment]
Looks like the `pyg` package is needed too still:

image

**Comment by AyodeAwe** [comment]
wholegraph seems needed too:

**Comment by AyodeAwe** [comment]
Docs build now passing:

image
https://github.com/rapidsai/cugraph/actions/runs/12280428843/job/34270317614?pr=4662#step:10:11205

**Comment by AyodeAwe** [comment]
@BradReesWork for a second review on this.

I've had to re-add the external packages previously removed due to the documentation build still needing it (see comments above this one).

**Review by BradReesWork — APPROVED** [review]

**Comment by AyodeAwe** [comment]
Upload confirmed from branch build:  https://github.com/rapidsai/cugraph/actions/runs/12317133575/job/34383555117#step:10:11097

**Pull request merged**
