### PR TITLE
Allow all integer types with renumber=False

### LINKED ISSUE #2670: [QST] Accept unsigned IDs?
#2337 has added a restriction in `simpleGraph.py` to only accept `int32` and `int64` IDs without renumbering. My code had `uint32`. 😭 The restriction could be easily relaxed to allow unsigned IDs, and it was working for me. Would it be okay to send a PR for this, or is there some concern about unsigned IDs?

Thank you!

### PR DESCRIPTION
**Pull request by darabos**
Resolves #2670.

`np.integer` is a superclass of all signed and unsigned integer types from `byte` to `longlong`. (https://numpy.org/doc/stable/reference/arrays.scalars.html) Let me know if that's too broad.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by alexbarghi-nv** [comment]
ok to test

**Comment by alexbarghi-nv** [comment]
@rlratzel could you mark this as ok to test?  It looks like I don't have the necessary privileges to do so.

**Comment by BradReesWork** [comment]
ok to test

**Comment by darabos** [comment]
Closing this per the discussion in #2670. Thanks!

**Pull request closed without merging**
