### PR TITLE
[REVIEW] Drop `cython` from run requirements

### PR DESCRIPTION
**Pull request by jakirkham**
As `cython` is only needed to build the Python bindings and does not contain any needed runtime libraries, drop it from the run requirements.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks Mike! 😄

**Comment by mike-wendt** [comment]
@jakirkham looks like we need Cython https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cugraph/job/prb/job/cugraph-cpu-build/2325/consoleFull#L1,447

**Comment by jakirkham** [comment]
That's odd. It is pointing to that coming from the `setup.py`. Why would that be called during runtime? 🤔

**Comment by jakirkham** [comment]
Ah! It's because the [Python package doesn't list the requirement]( https://github.com/rapidsai/cugraph/blob/fa98f611c4762800963324c5db87522d319cb80a/conda/recipes/cugraph/meta.yaml#L25-L29 ) so it is expect the C++ package to supply the dependency. Will push a fix.

**Comment by jakirkham** [comment]
Have pushed a fix. Let's see what CI thinks 🙂

**Comment by jakirkham** [comment]
It looks like it builds. However there are unit test failures ( likely due to the cuDF refactor https://github.com/rapidsai/cudf/pull/3254 ). This can safely wait until things are updated.

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by jakirkham** [comment]
Thanks! 😄

**Pull request merged**
