### PR TITLE
[REVIEW] Weighted Jaccard bindings

### PR DESCRIPTION
**Pull request by aschaffer**
Weighted Jaccard bindings out of branch-0.6 w/ latest RMM changes included. Test included, but no Networkx comparison, because Networkx doesn't support weighted Jaccard.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by kkraus14** [comment]
add to whitelist

**Comment by BradReesWork** [comment]
The ChangeLog needs to be updated

**Comment by aschaffer** [comment]
OK, CHANGELOG.md updated.

**Pull request merged**
