### PR TITLE
Removed outdated statement in readme

### PR DESCRIPTION
**Pull request by afender**
Reported by @Salonijain27

### CODE REVIEW

**Comment by afender** [comment]
rerun test

**Comment by afender** [comment]
rerun tests

**Comment by afender** [comment]
rerun tests

**Comment by afender** [comment]
@raydouglass it seems I cannot get tests to run for this PR :(
There is no real need for tests anyway (it is a simple readme edit) so you may directly merge it if you can.

**Comment by afender** [comment]
this has been addressed in #270

**Comment by raydouglass** [comment]
> @raydouglass it seems I cannot get tests to run for this PR :(

PRs that only change the readme or changelog do run in CI. Unfortunately, github still requires the status checks, so an admin needs to merge. I'm looking into how to handle this better.

**Comment by afender** [comment]
Good to know thanks

**Pull request closed without merging**
