### PR TITLE
[REVIEW] ENH Update Force Atlas 2 notebook, wrapper and coding style

### PR DESCRIPTION
**Pull request by hlinsen**
This PR updates the notebook for the blog post, the Python bindings and addresses the FIXMEs related to stream usage.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Review by ChuckHastings — APPROVED** [review]
lgtm

**Review by afender — COMMENTED** [review]
Consider removing your local output for the first notebook cell :

```
Requirement already satisfied: fa2 in /home/hlinsenmaier/anaconda3/envs/cugraph_dev2/lib/python3.8/site-packages (0.3.5)
 
Requirement already satisfied: scipy in /home/hlinsenmaier/anaconda3/envs/cugraph_dev2/lib/python3.8/site-packages (from fa2) (1.5.3)
 
Requirement already satisfied: numpy in /home/hlinsenmaier/anaconda3/envs/cugraph_dev2/lib/python3.8/site-packages (from fa2) (1.19.4)
 
Requirement already satisfied: tqdm in /home/hlinsenmaier/anaconda3/envs/cugraph_dev2/lib/python3.8/site-packages (from fa2) (4.52.0)
```

**Review by aschaffer — APPROVED** [review]

**Comment by hlinsen** [comment]
> Consider removing your local output for the first notebook cell :
> 
> ```
> Requirement already satisfied: fa2 in /home/hlinsenmaier/anaconda3/envs/cugraph_dev2/lib/python3.8/site-packages (0.3.5)
>  
> Requirement already satisfied: scipy in /home/hlinsenmaier/anaconda3/envs/cugraph_dev2/lib/python3.8/site-packages (from fa2) (1.5.3)
>  
> Requirement already satisfied: numpy in /home/hlinsenmaier/anaconda3/envs/cugraph_dev2/lib/python3.8/site-packages (from fa2) (1.19.4)
>  
> Requirement already satisfied: tqdm in /home/hlinsenmaier/anaconda3/envs/cugraph_dev2/lib/python3.8/site-packages (from fa2) (4.52.0)
> ```



> Consider removing your local output for the first notebook cell :
> 
> ```
> Requirement already satisfied: fa2 in /home/hlinsenmaier/anaconda3/envs/cugraph_dev2/lib/python3.8/site-packages (0.3.5)
>  
> Requirement already satisfied: scipy in /home/hlinsenmaier/anaconda3/envs/cugraph_dev2/lib/python3.8/site-packages (from fa2) (1.5.3)
>  
> Requirement already satisfied: numpy in /home/hlinsenmaier/anaconda3/envs/cugraph_dev2/lib/python3.8/site-packages (from fa2) (1.19.4)
>  
> Requirement already satisfied: tqdm in /home/hlinsenmaier/anaconda3/envs/cugraph_dev2/lib/python3.8/site-packages (from fa2) (4.52.0)
> ```

Fixed in commit https://github.com/rapidsai/cugraph/commit/cc7124cf9953b94608bcd016de4ad8c18d422094

**Review by BradReesWork — APPROVED** [review]

**Review by afender — APPROVED** [review]
lgtm!

**Review by ajschmidt8 — CHANGES_REQUESTED** [review]
Looks good. We'll need the new Notebook dependencies added to our `rapids-notebook-env` metapackage below. Please open a PR for that before this can be merged. Also, if these new dependencies change frequently, please consider pinning them as well (though I'll leave that to your discretion since I don't know much about them).

https://github.com/rapidsai/integration/blob/branch-0.17/conda/recipes/rapids-notebook-env/meta.yaml

**Review by ajschmidt8 — APPROVED** [review]
PR https://github.com/rapidsai/integration/pull/174 is merged, so this is good to go. thanks Hugo

**Pull request merged**
