### PR TITLE
MGPropertyGraph: fix OOM when renumbering by type

### LINKED ISSUE #3110: [BUG]: MGPropertyGraph renumber by type OOM
### Version

23.02

### Which installation method(s) does this occur on?

_No response_

### Describe the bug.

When calling e.g. `MGPropertyGraph.renumber_vertices_by_type`, all data for one type goes to a single partitions, which can easily cause OOM.

One way to address this is for renumbering by type to sort values on an additional column such as previous IDs, which will allow data for a single type to be split across partitions.

### Minimum reproducible example

_No response_

### Relevant log output

_No response_

### Environment details

_No response_

### Other/Misc.

_No response_

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

### PR DESCRIPTION
**Pull request by eriknw**
Fixes #3110

Previously, all data for a single type would be collected in a single partition, which could easily overwhelm a worker or GPU.

We now sort by multiple columns to ensure data can be evenly distributed.

### CODE REVIEW

**Review by alexbarghi-nv — APPROVED** [review]
👍

**Comment by alexbarghi-nv** [comment]
Looks good; was just wondering what the impact on runtime would be.

**Review by VibhuJawa — APPROVED** [review]
LGTM

**Pull request merged**
