### PR TITLE
Update for raft logger changes

### PR DESCRIPTION
**Pull request by vyasr**
This PR updates cugraph to use raft's updated logger implementation using [rapids-logger](https://github.com/rapidsai/rapids-logger).

This PR requires https://github.com/rapidsai/raft/pull/2530.

Contributes to https://github.com/rapidsai/build-planning/issues/104

### CODE REVIEW

**Comment by vyasr** [comment]
The devcontainer failures are expected since I haven't set that case up to pull the conda packages from the raft PR. That won't be tested until we merge that one.

**Review by bdice — APPROVED** [review]

**Review by jameslamb — APPROVED** [review]

**Review by BradReesWork — APPROVED** [review]

**Pull request merged**
