### PR TITLE
removed docs from cugraph build defaults and updated docs clean

### LINKED ISSUE #2789: [FEA] build.sh should not build docs by default
**Describe the solution you'd like and any additional context**
The build.sh script currently tries and build docs by default.   We should make building docs as an option since the Sphinx packages are not included in the conda environment by default 

Just need to removed the "buildAll" flag in the script

```
# Build the docs
if buildAll || hasArg docs; then
    if [ ! -d ${LIBCUGRAPH_BUILD_DIR} ]; then
        mkdir -p ${LIBCUGRAPH_BUILD_DIR}
        cd ${LIBCUGRAPH_BUILD_DIR}
        cmake -B "${LIBCUGRAPH_BUILD_DIR}" -S "${REPODIR}/cpp" \
              -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} \
              -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
	      ${CMAKE_GENERATOR_OPTION} \
              ${CMAKE_VERBOSE_OPTION}
    fi
    cd ${LIBCUGRAPH_BUILD_DIR}
    cmake --build "${LIBCUGRAPH_BUILD_DIR}" -j${PARALLEL_LEVEL} --target docs_cugraph ${VERBOSE_FLAG}
    cd ${REPODIR}/docs/cugraph
    make html
```

---
_For Developers below this line_

  - [] Code passes CI
  - [] Code uses Graph Primitives
  - [] Code in C++/CUDA layer
  - [] Code in C layer
  - [] Code in pylibcugraph Python layer
  - [] Code in cugraph Python layer
  - [] Documentation
  - [] Test cases at each layer (for MG tests, a note in the PR description indicating the new/existing MG tests were run and passed)

### LINKED ISSUE #2812: [FEA] build.sh clean should remove docs/cugraph/source/api_docs/api
build.sh clean in cugraph should remove docs/cugraph/source/api_docs/api
These are generated in the build.sh docs and make html from the docs directory. Files in this directory can prevent doc regeneration.

### PR DESCRIPTION
**Pull request by acostadon**
removed docs from default cugraph build behavior
added additional generated directory to docs clean target

closes #2789 
closes #2812

### CODE REVIEW

**Review by BradReesWork — APPROVED** [review]

**Comment by BradReesWork** [comment]
@acostadon line 44 needs to be updated to remove "docs" from list of default action

**Review by BradReesWork — CHANGES_REQUESTED** [review]
fix line 44

**Review by rlratzel — APPROVED** [review]

**Comment by rlratzel** [comment]
rerun tests

reason: style check had http errors, hopefully temporary.

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
