### PR TITLE
Remove `dask_cudf` dataframe for the `_make_plc_graph` while creating `cugraph.Graph` 

### PR DESCRIPTION
**Pull request by VibhuJawa**
This PR attempts to fix https://github.com/rapidsai/cugraph/issues/3790 

Please note that I  have not being able to cause failure locally so it is really hard for me to know if it actually fixes anything or not  . 

MRE being used to test locally: https://gist.github.com/VibhuJawa/4b1ec24022b6e2dd7879cd2e8d3fab67

CC: @jnke2016 , @rlratzel ,

CC:  @rjzamora , Please let me know what i can do better here.

### CODE REVIEW

**Review by rlratzel — APPROVED** [review]
Thanks Vibhu!

**Review by rlratzel — APPROVED** [review]

**Review by jnke2016 — APPROVED** [review]

**Pull request merged**
