### PR TITLE
[REVIEW] Update prebuild.sh

### PR DESCRIPTION
**Pull request by msadang**
Update conda upload versions for new supported CUDA/Python

Edited ci/cpu/prebuild.sh with CUDA 10.1 and python 3.7 as new defaults.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by raydouglass** [comment]
rerun tests

**Comment by dillon-cullinan** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Pull request merged**
