### PR TITLE
Refactor mg symmetrize tests 

### LINKED ISSUE #2277: [BUG] Broken MG tests caused by a change in the symmetrize function definition
The function transforming an asymmetric `dataframe` to a symmetric `dataframe` was recently refactored and part of the change was the function definition which is breaking the `mg symmetrize` tests. 

**Old function definition**
`symmetrize(source_col, dest_col, value_col=None, multi=False, symmetrize=True)`

**New function definition**
`symmetrize(input_df, source_col_name, dest_col_name, value_col_name=None, multi=False, symmetrize=True)`

### PR DESCRIPTION
**Pull request by jnke2016**
This PR refactors and fixes mg symmetrize tests
closes #2277

### CODE REVIEW

**Review by betochimas — APPROVED** [review]
I appreciate the updated testing refactoring, the main logic of the tests is intact with improved naming and relevant helpers. The debugging code if symmetrized edges aren't present also helps.

**Review by rlratzel — APPROVED** [review]

**Review by alexbarghi-nv — APPROVED** [review]
LGTM

**Review by acostadon — APPROVED** [review]
No recommendations here. looks great.

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
