### PR TITLE
Update FAISS to 1.7.0

### LINKED ISSUE #1440: [BUG] The BUILD_STATIC_FAISS option needs to be updated for libfaiss 1.7
cuGraph needs to update its `CMakeLists.txt` file to support the `BUILD_STATIC_FAISS` option now that it has upgraded to libfaiss 1.7.0.

This can be done by applying the same changes cuML did in https://github.com/rapidsai/cuml/pull/3509

### PR DESCRIPTION
**Pull request by BradReesWork**
upgraded FAISS to version 1.7

closes #1440

### CODE REVIEW

**Review by afender — APPROVED** [review]

**Review by ajschmidt8 — APPROVED** [review]

**Comment by BradReesWork** [comment]
@gpucibot merge

**Review by rlratzel — APPROVED** [review]
LGTM.

This other issue isn't urgent for unblocking builds now, but it will still need to be addressed as well at some point if we want to keep a static build option: https://github.com/rapidsai/cugraph/issues/1440

**Comment by rlratzel** [comment]
closes https://github.com/rapidsai/cugraph/issues/1440

**Comment by rlratzel** [comment]
@gpucibot merge

**Pull request merged**
