### PR TITLE
[REVIEW] BUG segfault in python test suite

### PR DESCRIPTION
**Pull request by afender**
https://github.com/rapidsai/cugraph/pull/1198#issuecomment-705207768
- added lib<cudf/rmm> to improve conda resolution and avoid versions mismatch 
- nccl from 2.5 to 2.7

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Review by BradReesWork — APPROVED** [review]

**Comment by efajardo-nv** [comment]
We also started getting segfaults in our CI builds.
https://github.com/rapidsai/clx/issues/249

**Comment by afender** [comment]
rerun tests

**Review by rlratzel — CHANGES_REQUESTED** [review]
Do you also need to update the conda recipes with the new nccl requirement?
`conda/recipes/cugraph/meta.yaml` 
`conda/recipes/libcugraph/meta.yaml`

**Comment by BradReesWork** [comment]
rerun tests

**Comment by rlratzel** [comment]
rerun tests

**Review by rlratzel — APPROVED** [review]

**Review by BradReesWork — APPROVED** [review]

**Review by ajschmidt8 — APPROVED** [review]

**Pull request merged**
