### PR TITLE
Code cleanup (remove dead code and move legacy files to the legacy directory)

### PR DESCRIPTION
**Pull request by seunghwak**
Code clean-up before bringing bigger changes to the codebase.

Breaking because several replaced legacy functions are deleted (I guess no one is directly using them).

### CODE REVIEW

**Comment by ChuckHastings** [comment]
Some of these changes are probably premature.

Legacy jaccard/overlap is still in use by python.  We also don't have an implementation for the weighted variation.

**Comment by seunghwak** [comment]
> Legacy jaccard/overlap is still in use by python.

I wonder why compile didn't fail in my local system. Aren't we calling these in cython/c_api?

**Comment by seunghwak** [comment]
It seems like `extract_subgraph_vertex` is also used in python as well (isn't this induced subgraph?) But it seems like this wasn't called in cython/c_api. Do we have another mechanism to call C++ function from python (without relying on c_api or cython)?

**Comment by ChuckHastings** [comment]
There was, before `cython.cu` a mechanism that we used for calling legacy algorithms.  Not everything was migrated to use `python.cu`, because we decided to create the C API/PLC layer and stopped migrating things to `python.cu`.

**Review by naimnv — APPROVED** [review]

**Comment by rlratzel** [comment]
rerun tests

reason: test timeout, try rerunning for now but may have to look into it if it persists.

**Review by ChuckHastings — APPROVED** [review]

**Review by naimnv — APPROVED** [review]

**Review by jnke2016 — APPROVED** [review]

**Comment by seunghwak** [comment]
rerun tests

**Pull request merged**
