### PR TITLE
added test cases and verified that algorithm works for undirected graphs

### LINKED ISSUE #2239: [BUG]test_mg_degree fails with an undirected graph
**Describe the bug**
When running test_mg_degree, the test fails with the undirected graph object.

**Expected behavior**
Results should be identical to running with a directed graph which passes.

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal run on DGX18]
 - Method of cuGraph install: [conda]
 
Error output
>       raise AssertionError(msg)
E       AssertionError: ColumnBase are different
E       
E       values are different (100.0 %)
E       [left]:  {'[0, 3, 11, 4, 0, 2, 0, 0, 1, 2, 17, 1, 0, 0, 2, 1, 2, 3, 0, 2, 2, 2, 3, 1, 0, 0, 3, 1, 2, 4, 1, 4, 2, 2]'}
E       [right]: {'[2, 4, 12, 4, 16, 5, 3, 2, 3, 3, 17, 9, 5, 2, 3, 1, 2, 6, 2, 4, 4, 2, 4, 4, 2, 2, 3, 3, 10, 6, 2, 5, 2, 2]'}

### PR DESCRIPTION
**Pull request by acostadon**
closes #2239

### CODE REVIEW

**Comment by acostadon** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by acostadon** [comment]
rerun tests

**Review by rlratzel — APPROVED** [review]
Looks good.

Note for later: in the future we'll be refactoring these to use the `datasets` API so we won't have to manually create paths to CSV files.

**Pull request merged**
