### PR TITLE
[REVIEW] Pin `dask` and `distributed` for release

### PR DESCRIPTION
**Pull request by galipremsagar**
This PR pins `dask` and `distributed` to `2022.11.1` for `22.12` release.
xref: https://github.com/rapidsai/cudf/pull/12165

### CODE REVIEW

**Review by raydouglass — APPROVED** [review]

**Comment by raydouglass** [comment]
@gpucibot merge

**Review by BradReesWork — APPROVED** [review]

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
@gpucibot merge

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
