### PR TITLE
Clean up nullptr cuda_stream_view arguments

### PR DESCRIPTION
**Pull request by hlinsen**
Cugraph fix for: https://github.com/rapidsai/cugraph/issues/1499

### CODE REVIEW

**Review by BradReesWork — APPROVED** [review]

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Review by afender — APPROVED** [review]
Thanks Hugo 👍

**Comment by afender** [comment]
We need to merge #1498 before rerunning tests

**Review by afender — APPROVED** [review]

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
