### PR TITLE
[REVIEW] Fix cluster startup script

### PR DESCRIPTION
**Pull request by VibhuJawa**
This PR fixes  cluster startup script

### CODE REVIEW

**Review by alexbarghi-nv — APPROVED** [review]
This matches the options that work for me.  Approved.

**Review by BradReesWork — APPROVED** [review]

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Review by rlratzel — APPROVED** [review]
Thanks, I actually had to make the same changes to a PR I haven't submitted yet.

**Comment by rlratzel** [comment]
@gpucibot merge

**Pull request merged**
