### PR TITLE
[REVIEW] BUG fix misspelling of function calls in asserts causing debug build to fail

### PR DESCRIPTION
**Pull request by ChuckHastings**
Some of the pattern accelerator calls have the misspelled calls in assert messages.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Review by BradReesWork — APPROVED** [review]

**Review by seunghwak — APPROVED** [review]
Thanks for fixing my mistakes :-)

**Comment by ChuckHastings** [comment]
rerun tests

**Comment by ChuckHastings** [comment]
rerun tests

**Comment by abellina** [comment]
@ChuckHastings sorry I am not familiar with this change, maybe I was tagged by mistake.

**Comment by ChuckHastings** [comment]
> @ChuckHastings sorry I am not familiar with this change, maybe I was tagged by mistake.

No worries.  @BradReesWork probably tagged you accidentally.

**Pull request merged**
