### PR TITLE
Update probability params for RMAT call to match Graph500

### PR DESCRIPTION
**Pull request by rlratzel**
Update probability params for RMAT call to match Graph500.

This PR also contains a necessary change to the `libcugraph_etl` CMakeLists.txt file that fixes a problem with the GPU arch detection and filtering that was causing the build to fail.

### CODE REVIEW

**Comment by rlratzel** [comment]
rerun tests

Forward merge from 21.12 now in place, build should pass.

**Comment by rlratzel** [comment]
rerun tests

**Review by jnke2016 — APPROVED** [review]

**Comment by seunghwak** [comment]
@rlratzel Better fix comments in https://github.com/rapidsai/cugraph/blob/branch-21.12/python/cugraph/cugraph/generators/rmat.py#L299 as well.

**Comment by rlratzel** [comment]
rerun tests

Re-running now that style checker has been updated for latest clang-tools.

**Review by seunghwak — APPROVED** [review]

**Review by raydouglass — APPROVED** [review]

**Review by BradReesWork — APPROVED** [review]

**Comment by rlratzel** [comment]
@gpucibot merge

**Pull request merged**
