### PR TITLE
Rename `cugraph-nx` to `nx-cugraph`

### PR DESCRIPTION
**Pull request by eriknw**
We decided to rename `cugraph-nx` to `nx-cugraph` to follow (and help establish) conventions for names of networkx backends. See: https://github.com/networkx/networkx/discussions/6883

This PR was created from the following commands:
```sh
mv notebooks/ ../notebooks-bak
find * -type f -print0 | xargs -0 sed -i 's/cugraph_nx/nx_cugraph/g'
find * -type f -print0 | xargs -0 sed -i 's/cugraph-nx/nx-cugraph/g'
git mv ./conda/recipes/cugraph-nx ./conda/recipes/nx-cugraph
git mv ./python/cugraph-nx ./python/nx-cugraph
git mv ./python/nx-cugraph/cugraph_nx ./python/nx-cugraph/nx_cugraph
mv ../notebooks-bak/ notebooks
```
(a more reliable bash script would ensure the destination of `git mv` does not exist yet, b/c if the destination is a directory, it will happily--and incorrectly--move the target _into_ the directory)
```sh
# Make sure everything got renamed correctly
git grep -i 'cugraph.nx'
find . -iname '*cugraph*nx*' -print
```
Should we remove `cugraph-nx` nightlies once this is merged?

### CODE REVIEW

**Comment by eriknw** [comment]
Aw, CI failure when building `cugraph` (_not_ `nx-cugraph`) wheel b/c it can't find `libraft.so`.

**Comment by betochimas** [comment]
> Aw, CI failure when building `cugraph` (_not_ `nx-cugraph`) wheel b/c it can't find `libraft.so`.

Is this related? https://github.com/rapidsai/graph_dl/issues/295. Also, are other PRs having the same problem or is it just this one?

**Comment by betochimas** [comment]
Do you plan on leaving in the `cugraph-nx` package in this PR and then removing it in another PR, or will it happen here? At the moment, I see `cugraph-nx` (all the files are removed, but the file structure is still there) and `nx-cugraph`. Not sure if it's just my environment or not

**Comment by eriknw** [comment]
> Do you plan on leaving in the cugraph-nx package in this PR and then removing it in another PR, or will it happen here? At the moment, I see cugraph-nx (all the files are removed, but the file structure is still there) and nx-cugraph. Not sure if it's just my environment or not

Great question--thanks for the careful attention. The old directory is there for you locally b/c it must not be empty (perhaps `.ruff_cache`?). We can browse the file structure for a given commit, and here you see `cugraph-nx` does not exist:
https://github.com/eriknw/cugraph/tree/6b0eca6db0da76a9b1f7beb0f484db7ae669a590/python

**Comment by betochimas** [comment]
Here was my review workflow: 1) I built, cleaned, and re-built cugraph and nx-cugraph, 2) I ran all nx-cugraph tests and used the package in my env, 3) looked for all mentions to 'cugraph_nx', 'cugraph-nx', and 'cnx'.

There's some uses of 'cnx' (ex: cnx_path, cnx_mod) and 'cG' (instead of 'Gcg') within `test_match_api.py` and `test_convert.py` respectively. All of these are minor though, so up to you. I would approve

**Review by rlratzel — APPROVED** [review]
LGTM, nothing jumped out as missing. Thanks!

**Comment by rlratzel** [comment]
> There's some uses of 'cnx' (ex: cnx_path, cnx_mod) and 'cG' (instead of 'Gcg') within test_match_api.py and test_convert.py respectively. All of these are minor though, so up to you. I would approve

I was not as careful reviewing as @betochimas .  The items he pointed out might be good to change if it's not too much trouble.

**Review by raydouglass — APPROVED** [review]

**Comment by eriknw** [comment]
> Here was my review workflow: 1) I built, cleaned, and re-built cugraph and nx-cugraph, 2) I ran all nx-cugraph tests and used the package in my env, 3) looked for all mentions to 'cugraph_nx', 'cugraph-nx', and 'cnx'.
> 
> There's some uses of 'cnx' (ex: cnx_path, cnx_mod) and 'cG' (instead of 'Gcg') within `test_match_api.py` and `test_convert.py` respectively. All of these are minor though, so up to you. I would approve

Good approach, and good suggestions! I made the requested changes.

**Pull request merged**
