### PR TITLE
Update vertex_frontier_t to take unsorted (tagged-)vertex list with possible duplicates

### PR DESCRIPTION
**Pull request by seunghwak**
Partially address https://github.com/rapidsai/cugraph/issues/2580

Update vertex_frontier_t to take unsorted input (tagged-)vertex list with possible duplicates.

This will be used to define a selection primitive. The primitive needs to take a (tagged-)vertex list to support Node2Vec style algorithms (tagged with the predecessor vertex ID or some derived property from the current vertex predecessor vertex pairs).

Breaking as primitives API has been changed (`vertex_frontier_t` and `transform_reduce_v_frontier_outgoing_e_by_dst`).

### CODE REVIEW

**Comment by seunghwak** [comment]
rerun tests

**Review by jnke2016 — APPROVED** [review]

**Review by ChuckHastings — APPROVED** [review]

**Comment by ChuckHastings** [comment]
rerun tests

**Review by naimnv — APPROVED** [review]
Looks good to me. Had to look into the return type of thrust::unique, otherwise changes are easy to follow. 

```
        merged_vertices.resize(
          thrust::distance(merged_pair_first,
                           thrust::unique(handle_ptr_->get_thrust_policy(),
                                          merged_pair_first,
                                          merged_pair_first + merged_vertices.size())),
```

**Comment by seunghwak** [comment]
> Looks good to me. Had to look into the return type of thrust::unique, otherwise changes are easy to follow.
> 
> ```
>         merged_vertices.resize(
>           thrust::distance(merged_pair_first,
>                            thrust::unique(handle_ptr_->get_thrust_policy(),
>                                           merged_pair_first,
>                                           merged_pair_first + merged_vertices.size())),
> ```

You'll soon get very familiar with thrust (as you now already know, cuGraph is basically thrust + primitives).

**Comment by ChuckHastings** [comment]
@gpucibot merge

**Pull request merged**
