### PR TITLE
Use CUB 1.15.0's new segmented sort

### PR DESCRIPTION
**Pull request by seunghwak**
- [x] Update neighbor sort to use the new segmented sort.
- [x] Update copy_v_transform_reduce_key_aggregated_out_nbr to use the new segmented sort (instead of a global sort) for the data already sorted by major vertices (e.g. previously segmented sort was slower than the global sort).

### CODE REVIEW

**Review by ChuckHastings — APPROVED** [review]
LGTM - still waiting on the rapids-make change.

**Comment by seunghwak** [comment]
> LGTM - still waiting on the rapids-make change.

Thanks for a quick review but this PR is still a work-in-progress :-)

I will also experiment with this in copy_v_key_aggregated_out_nbr to see whether I can make the primitive faster.
https://github.com/rapidsai/cugraph/blob/branch-22.02/cpp/include/cugraph/prims/copy_v_transform_reduce_key_aggregated_out_nbr.cuh#L352

This pulls updates from #1976, so that PR may better be reviewed & merged first :-)

**Comment by ChuckHastings** [comment]
https://github.com/rapidsai/rapids-cmake/pull/138 tracks the work to upgrade thrust/cub to version 1.15.0

**Review by kaatish — APPROVED** [review]

**Comment by robertmaynard** [comment]
The rapids-cmake PR has been merged. 

I believe you can also remove the following workaround: https://github.com/rapidsai/cugraph/blob/branch-22.02/cpp/cmake/thirdparty/get_thrust.cmake#L21

**Review by ChuckHastings — APPROVED** [review]

**Pull request merged**
