### PR TITLE
drop fa2 cpu code

### PR DESCRIPTION
**Pull request by BradReesWork**
update the ForceAtlas notebook to not use fa2 python package

### CODE REVIEW

**Review by ChuckHastings — CHANGES_REQUESTED** [review]
Couple of minor edits/questions.

**Comment by BradReesWork** [comment]
> 

Sorry, pushed the wrong version.

**Review by ChuckHastings — APPROVED** [review]
LGTM

**Review by rlratzel — APPROVED** [review]
LGTM

One suggestion (optional): instead of the 
```
start = time.time()
...
elapsed = time.time() - start
```
you could use the `%%time` or `%%timeit` cell magic.

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
