### PR TITLE
[DO NOT MERGE] Testing RAFT PR 690

### PR DESCRIPTION
**Pull request by vinaydes**
This PR is just to test if changes RAFT PR 690 works fine with cuGraph.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by BradReesWork** [comment]
rerun tests

**Comment by ChuckHastings** [comment]
Can we close this?  RAFT PR 690 was merged, so I think this is no longer relevant,.

**Comment by vinaydes** [comment]
Closing now, sorry for delay.

**Pull request closed without merging**
