### PR TITLE
Bug fix cmake abi - support old ABI

### PR DESCRIPTION
**Pull request by ChuckHastings**
As we discussed in slack... I added back support for building with old ABI - but default is still new ABI.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by kkraus14** [comment]
add to whitelist

**Comment by aschaffer** [comment]
Ack-ed.

**Comment by aschaffer** [comment]
Verified. Build clean, all GTESTs pass. cmake command:
cmake .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX

**Pull request merged**
