### PR TITLE
Issue 59 Bug fix

### PR DESCRIPTION
**Pull request by jwyles**
Close Issue #59 
Fixed segfault issue by adding checks into graph methods for computing edge list and transpose. Added some additional helper methods on python graph object. Added tests verifying bug fix and fixed some issue in existing tests.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by kkraus14** [comment]
add to whitelist

**Comment by BradReesWork** [comment]
PLease update the ChangeLog

**Pull request merged**
