### PR TITLE
build.sh switch to use `RAPIDS` magic value

### PR DESCRIPTION
**Pull request by robertmaynard**
rapids-cmake 23.02 is deprecating the magic value of `ALL` since it doesn't cleanly map to the cmake magic value of `all`. Instead we use `RAPIDS` which better represents the architectures we are building for.

### CODE REVIEW

**Review by BradReesWork — APPROVED** [review]

**Review by rlratzel — APPROVED** [review]

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Pull request merged**
