### PR TITLE
Adding new primitives: copy_v_transform_reduce_key_aggregated_out_nbr & transform_reduce_by_adj_matrix_row|col_key_e bug fixes

### PR DESCRIPTION
**Pull request by seunghwak**
bug fixes

### CODE REVIEW

**Comment by seunghwak** [comment]
@ChuckHastings If you have verified Louvain is working and if there is no need to push more commits to this PR, we can review this PR and merge.

**Comment by seunghwak** [comment]
rerun tests

**Review by ChuckHastings — APPROVED** [review]
I have tested these changes with experimental Louvain and they work.

**Review by BradReesWork — APPROVED** [review]

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
