### PR TITLE
[REVIEW] ENH Added min CUDA version check to MG Louvain

### PR DESCRIPTION
**Pull request by rlratzel**
Added a check for CUDA runtime version to be >= 10.2 to the MG Louvain API, which makes for a more user-friendly error message.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Review by BradReesWork — APPROVED** [review]

**Review by Iroy30 — APPROVED** [review]

**Comment by rlratzel** [comment]
rerun tests

**Review by afender — APPROVED** [review]

**Comment by rlratzel** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by rlratzel** [comment]
rerun tests

reason: a `git clone` step failed

**Comment by rlratzel** [comment]
rerun tests

reason: `FATAL: Could not pull image: gpuci/rapidsai:0.16-cuda10.1-devel-ubuntu16.04-py3.7`

**Comment by mike-wendt** [comment]
FYI `gpuCI/cugraph/pr-builder` is showing failure, but do not retry just yet. It is marked as failed due to killing the retried job. It will update when this [run](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cugraph/job/prb/job/cugraph-prb/2382/) is completed

**Comment by mike-wendt** [comment]
Looks like test [failures](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci-a100/job/cugraph/job/prb/job/cugraph-gpu-build/290/testReport/) with CUDA 11 testing; your judgement call on how to proceed @rlratzel @BradReesWork

**Pull request merged**
