### PR TITLE
[REVIEW] update graph to accept multiple weights

### PR DESCRIPTION
**Pull request by Iroy30**
Updates graph and symmetrize to accept and store multiple weights

related to #1373

### CODE REVIEW

**Comment by Iroy30** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by hlinsen** [comment]
Thanks Ishika. PR looks good, just misses a test for the new functionality.
Let's also add an issue to generalize multiple weights support since this PR targets  https://github.com/rapidsai/cugraph/issues/1373 specifically.

**Comment by Iroy30** [comment]
To be addressed in new graph classes in future. #1373 is being handled with a utility function.

**Pull request closed without merging**
