### PR TITLE
Remove GNN Packages

### PR DESCRIPTION
**Pull request by alexbarghi-nv**
Removes the GNN packages, which are now part of [cugraph-gnn](https://github.com/rapidsai/cugraph-gnn).

### CODE REVIEW

**Review by jameslamb — COMMENTED** [review]
I pulled this branch and searched like this:

```shell
git grep -E -i 'dgl|pyg'
```

Found some more things that I think should be deleted.

test files:

* https://github.com/rapidsai/cugraph/blob/branch-24.12/ci/run_cugraph_pyg_pytests.sh
* https://github.com/rapidsai/cugraph/blob/branch-24.12/ci/run_cugraph_dgl_pytests.sh

test code:

https://github.com/rapidsai/cugraph/blob/c712a9857abac9d033fda41278cc07ce51059d34/ci/test.sh#L102-L107

the conda recipes:

* https://github.com/rapidsai/cugraph/tree/branch-24.12/conda/recipes/cugraph-dgl
* https://github.com/rapidsai/cugraph/tree/branch-24.12/conda/recipes/cugraph-pyg

Test coverage config:

https://github.com/rapidsai/cugraph/blob/c712a9857abac9d033fda41278cc07ce51059d34/python/.coveragerc#L4

https://github.com/rapidsai/cugraph/blob/c712a9857abac9d033fda41278cc07ce51059d34/python/.coveragerc#L8

**Comment by alexbarghi-nv** [comment]
> I pulled this branch and searched like this:
> 
> ```shell
> git grep -E -i 'dgl|pyg'
> ```
> 
> Found some more things that I think should be deleted.
> 
> test files:
> 
> * https://github.com/rapidsai/cugraph/blob/branch-24.12/ci/run_cugraph_pyg_pytests.sh
> * https://github.com/rapidsai/cugraph/blob/branch-24.12/ci/run_cugraph_dgl_pytests.sh
> 
> test code:
> 
> https://github.com/rapidsai/cugraph/blob/c712a9857abac9d033fda41278cc07ce51059d34/ci/test.sh#L102-L107
> 
> the conda recipes:
> 
> * https://github.com/rapidsai/cugraph/tree/branch-24.12/conda/recipes/cugraph-dgl
> * https://github.com/rapidsai/cugraph/tree/branch-24.12/conda/recipes/cugraph-pyg
> 
> Test coverage config:
> 
> https://github.com/rapidsai/cugraph/blob/c712a9857abac9d033fda41278cc07ce51059d34/python/.coveragerc#L4
> 
> https://github.com/rapidsai/cugraph/blob/c712a9857abac9d033fda41278cc07ce51059d34/python/.coveragerc#L8

These should be taken care of now.

**Comment by alexbarghi-nv** [comment]
The benchmarks are going to stay for now; those will go away in 25.02.

**Review by KyleFromNVIDIA — APPROVED** [review]

**Review by ChuckHastings — APPROVED** [review]

**Comment by bdice** [comment]
I merged in the upstream and resolved conflicts with #4762. Based on the mostly-complete CI run from 0694814, I think we might be close to having passing CI now that RAFT kernel symbol failures are resolved. We will know in the morning. 👍

**Review by bdice — APPROVED** [review]

**Review by rlratzel — APPROVED** [review]
I think this looks right but I admit I'm relying more on the passing CI status and working nightly packages to say for sure.

**Pull request merged**
