### PR TITLE
updated release performance notebook to also measure using Nx as imput

### PR DESCRIPTION
**Pull request by BradReesWork**
Update the release notebook to produce speedup metrics of using a NetworkX object as the input Graph.

### CODE REVIEW

**Review by acostadon — APPROVED** [review]
Only saw the typo I noted. Ran well for me. no other comments

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by rlratzel** [comment]
Updated build env has compatible NetworkX/SciPy packages.

rerun tests

**Comment by BradReesWork** [comment]
@gpucibot merge

**Review by rlratzel — APPROVED** [review]
Nothing jumped out, but I was wondering if you really wanted to leave the outputs of your last run for all your cells in place. If not, you could do a "clear all outputs" before saving from jupyter to allow users to start the notebook from a clean state. That would reset the "execution count" for each cell, clear the outputs printing "Reading ./data/...", etc.

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
