### PR TITLE
Use numba>=0.57.

### PR DESCRIPTION
**Pull request by bdice**
This updates to `numba>=0.57`, which is needed to avoid dependency conflicts with https://github.com/rapidsai/cudf/pull/13337/.

Please merge after https://github.com/rapidsai/cudf/pull/13337/.

### CODE REVIEW

**Review by raydouglass — APPROVED** [review]

**Review by rlratzel — APPROVED** [review]
Thanks for updating our `is_pascal` utility too.

**Comment by bdice** [comment]
@raydouglass @rlratzel This might need re-approved since I opened it from draft state. It's ready to merge now that new cudf nightly builds have been uploaded.

**Review by raydouglass — APPROVED** [review]

**Review by BradReesWork — APPROVED** [review]

**Comment by bdice** [comment]
Depends on #3607, then this is ready to re-run CI and merge.

**Comment by rlratzel** [comment]
I ended up merging the changes from this PR into #3607 in order to properly update numba pins to match cudf's, in order to resolve a CI failure when using the latest cudf.

**Comment by bdice** [comment]
Closing in favor of #3607.

**Pull request closed without merging**
