### PR TITLE
Fixed FatalError typo in trianges_counting.cpp

### PR DESCRIPTION
**Pull request by ShadenSmith**
"to high" -> "too high"

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by jrhemstad** [comment]
okay to test

**Comment by afender** [comment]
rerun tests

**Comment by afender** [comment]
Good catch @ShadenSmith.Thanks for fixing that!
We try to update the `changelog.md` for each PR. That would be ideal if you could add your PR in the changelog.

**Pull request merged**
