### PR TITLE
Add `node2vec` wrappers to pylibcugraph

### LINKED ISSUE #2058: [ENH] Add `node2vec` API to cugraph
node2vec has been implemented in libcugraph, in the C++ library. The task is to add the API to `pylibcugraph` and `cugraph`, as well as writing tests and writing clear documentation for these node2vec methods

- [x] Add initial set of unit tests in `cugraph` for desired cugraph node2vec API
- [x] Write initial implementation in cugraph for `node2vec`, which either calls stubbed-out `pylibcugraph.node2vec()` or hardcodes fake data.
- [x] Add initial set of unit tests in `pylibcugraph`. These will be written to exercise the requirements of the `cugraph.node2vec()` implementation.
- [x] Write initial implementation in pylibcugraph for `node2vec`, which either calls a stubbed-out `node2vec` C API or hardcodes fake data.
- [x] Review https://github.com/rapidsai/cugraph/pull/2059
- [x] `cugraph.node2vec()` docstring
- [x] `pylibcugraph.node2vec()` docstring

### PR DESCRIPTION
**Pull request by betochimas**
Helps close #2058, when combined with a future PR for the cugraph layer implementation of node2vec, which depends on this PR. Ready for review. Disregard #2084 and #2063.

### CODE REVIEW

**Comment by ajschmidt8** [comment]
Removing myself as a reviewer since I don't see any files in this PR that I'm familiar enough with to effectively review.

**Comment by betochimas** [comment]
rerun tests

**Comment by betochimas** [comment]
rerun tests

**Review by BradReesWork — APPROVED** [review]

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
@gpucibot merge

**Comment by betochimas** [comment]
rerun tests

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
