### PR TITLE
Delete legacy renumbering implementation

### PR DESCRIPTION
**Pull request by ChuckHastings**
This code is no longer used.

### CODE REVIEW

**Review by seunghwak — APPROVED** [review]

**Comment by seunghwak** [comment]
Why's this breaking?

**Comment by ChuckHastings** [comment]
I labeled it breaking because it deletes a function from `functions.hpp`.  Anyone that wrote code that depended on that function will break.

It was unclear to me which things that break outside users warrant that label.  It doesn't break any python users... only if we have users of our legacy C++ API.

**Review by BradReesWork — APPROVED** [review]

**Review by aschaffer — APPROVED** [review]

**Review by Iroy30 — APPROVED** [review]
LGTM.

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
