### PR TITLE
Relax PyTorch upper bound (allowing 2.4)

### PR DESCRIPTION
**Pull request by jakirkham**
As the issue around PyTorch being built without NumPy was fixed in conda-forge, we can now relax these upper bounds to allow PyTorch 2.4.

xref: https://github.com/conda-forge/pytorch-cpu-feedstock/issues/254
xref: https://github.com/conda-forge/pytorch-cpu-feedstock/issues/266
xref: https://github.com/rapidsai/cugraph/pull/4615

### CODE REVIEW

**Review by alexbarghi-nv — APPROVED** [review]
👍

**Comment by jakirkham** [comment]
Odd looks the S3 upload of wheels built [on CI failed]( https://github.com/rapidsai/cugraph/actions/runs/11222827420/job/31196104848?pr=4703#step:9:175 ). Going to cancel builds and restart

```
[rapids-upload-to-s3] Path to upload is a directory, creating .tar.gz
./
./cugraph_equivariant_cu11-24.12.0a40-py3-none-any.whl
upload failed: - to s3://rapids-downloads/ci/cugraph/pull-request/4703/fb7a6a6/cugraph_wheel_python_cugraph-equivariant_cu11.tar.gz An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): We encountered an internal error. Please try again.
Error: Process completed with exit code 1.
```

**Review by jameslamb — APPROVED** [review]
great! Always happy to see a `<` removed when possible.

**Comment by jakirkham** [comment]
[One CI]( https://github.com/rapidsai/cugraph/actions/runs/11222827420/job/31200977238?pr=4703 ) build failed as it [pulled in CuPy 12.2.0]( https://github.com/rapidsai/cugraph/actions/runs/11222827420/job/31200977238?pr=4703#step:7:324 ) alongside [NumPy 2]( https://github.com/rapidsai/cugraph/actions/runs/11222827420/job/31200977238?pr=4703#step:7:432 ), which is [incompatible]( https://github.com/rapidsai/cugraph/actions/runs/11222827420/job/31200977238?pr=4703#step:7:990 )

Looks like this is due to a repodata patch not getting applied to older CuPy packages in conda-forge. Addressing in upstream PR: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/873

Not expecting any other action needed here (beyond restarting the failed build when the upstream PR lands)

**Comment by alexbarghi-nv** [comment]
WholeGraph feature store tests are failing.  I'm looking into it.

**Comment by jakirkham** [comment]
Thanks Alex! 🙏

Meaning the failures in [this CI job]( https://github.com/rapidsai/cugraph/actions/runs/11222827420/job/31200976952?pr=4703#step:7:5699 ):

```python
FAILED tests/data_store/test_gnn_feat_storage_wholegraph.py::test_feature_storage_wholegraph_backend - assert 0 > 0
FAILED tests/data_store/test_gnn_feat_storage_wholegraph.py::test_feature_storage_wholegraph_backend_mg - assert 0 > 0
```

Looks like that job does have CuPy 13.3.0 + NumPy 2, which are compatible. So this is unrelated to the CuPy repodata patch above

Agree these are worth looking into

Did notice this line when going through the log

```
pytorch                   2.4.1           cpu_mkl_py312hf535c18_100    conda-forge
```

So maybe this a different dependency resolution issue. Have a hunch as to what this might be, but will need to investigate further

**Comment by alexbarghi-nv** [comment]
> Thanks Alex! 🙏
> 
> Meaning the failures in [this CI job](https://github.com/rapidsai/cugraph/actions/runs/11222827420/job/31200976952?pr=4703#step:7:5699):
> 
> ```python
> FAILED tests/data_store/test_gnn_feat_storage_wholegraph.py::test_feature_storage_wholegraph_backend - assert 0 > 0
> FAILED tests/data_store/test_gnn_feat_storage_wholegraph.py::test_feature_storage_wholegraph_backend_mg - assert 0 > 0
> ```
> 
> Looks like that job does have CuPy 13.3.0 + NumPy 2, which are compatible. So this is unrelated to the CuPy repodata patch above
> 
> Agree these are worth looking into
> 
> Did notice this line when going through the log
> 
> ```
> pytorch                   2.4.1           cpu_mkl_py312hf535c18_100    conda-forge
> ```
> 
> So maybe this a different dependency resolution issue. Have a hunch as to what this might be, but will need to investigate further

Oh, good catch.  That is very likely the cause.

**Comment by alexbarghi-nv** [comment]
I'm having a hard time replicating that dependency resolution locally.  Instead, mamba is resolving:
```
  + pytorch                                  2.3.1  cuda120_py312h26b3cf7_300            conda-forge            25MB
```

**Comment by alexbarghi-nv** [comment]
This error goes away when adding `-c pytorch` and correctly installs `pytorch` from the `pytorch` channel.  Let me push a change to this PR.

**Comment by alexbarghi-nv** [comment]
It looks like we failed due to selecting an older version of `cupy`.  Can we safely bind `cupy` to `>=13.3` in `dependencies.yaml`? @jakirkham

**Comment by jakirkham** [comment]
Think this has to do with the issue mentioned above ( https://github.com/rapidsai/cugraph/pull/4703#issuecomment-2398056032 ), which was recently resolved

Let's give this another try

Am going to try without the `pytorch` channel if that is ok

Let's look at the results of that

We can then discuss after whether we want any more changes

**Comment by jakirkham** [comment]
Now seeing errors like these in failing CI jobs

```python
NotImplementedError: `ego_graph' is not implemented by ['cugraph'] backends. To remedy this, you may enable automatic conversion to more backends (including 'networkx') by adding them to `nx.config.backend_priority`, or you may specify a backend to use with the `backend=` keyword argument.
```

Are we missing something in cuGraph?

**Comment by jakirkham** [comment]
From offline discussion, sounds like this was fixed in PR: https://github.com/rapidsai/cugraph/pull/4717

Updated this PR to pull in those changes

**Comment by jakirkham** [comment]
Looks like this is passing! 🥳

@alexbarghi-nv @jameslamb would you like to give it one last look?

**Review by jameslamb — APPROVED** [review]
Looks fine to me. Now that we have CI set up in https://github.com/rapidsai/cugraph-gnn, can you replicate these changes over to there as well? Hopefully soon we can move `cugraph-dgl` and `cugraph-pyg` out of this repo completely and not have to do that duplicate work.

**Comment by jakirkham** [comment]
Resolved conflicts

Also done in PR: https://github.com/rapidsai/cugraph-gnn/pull/75

**Comment by jakirkham** [comment]
Thanks all! 🙏

**Pull request merged**
