### PR TITLE
C API updates for pagerank

### PR DESCRIPTION
**Pull request by ChuckHastings**
To address problems in nightly tests, we're going to update the python pagerank to use the PLC pagerank path.  In analyzing the code, @jnke2016 identified a feature not currently exposed by PLC and the C API - allowing the user to specify an initial guess for the page ranks.

This PR will expose that feature through the C API and PLC layers.

This PR will be incorporated into #2467 - both sets of changes are needed to pass CI.  Leave open until 2467 is merged.

### CODE REVIEW

**Comment by seunghwak** [comment]
What is PLC? pylibcugraph?

**Comment by ChuckHastings** [comment]
> What is PLC? pylibcugraph?

Yes

**Review by jnke2016 — APPROVED** [review]
Reviewed and tested. Looks good to me

**Comment by rlratzel** [comment]
These commits are in #2467 and have been approved by cpp codeowners there.

**Pull request closed without merging**
