### PR TITLE
Adds better reporting of server subprocess errors during testing

### LINKED ISSUE #3011: cugraph-service tests hide errors from server subprocess
The subprocess launched for cugraph-service-server during testing does not output the stderr/stdout to the console during a case when the server could not start or crashes (outside of a `CugraphServiceError` exception handler), making debugging hard.  This is especially difficult if it happens during a CI run, since the log will not contain any clues about why the server didn't start or crashed.

### PR DESCRIPTION
**Pull request by rlratzel**
closes #3011 

This PR adds a check for the server subprocess exitcode while waiting for it to start so it fails faster. Since it can fail faster, it also increases the wait to a full 60 seconds, which has shown to be helpful when starting a MG server that connects to a dask cluster.

It also includes the subprocess stdout/stderr output in the exception raised or to the console depending on how it exited to help debug why the server didn't start or crashed.

### CODE REVIEW

**Comment by rlratzel** [comment]
rerun tests

reason: checking if new nightly builds of conda dependencies resolves solver issue.

**Comment by rlratzel** [comment]
rerun tests

reason: merged https://github.com/rapidsai/cugraph/pull/3066 which should fix CI errors

**Review by BradReesWork — APPROVED** [review]

**Comment by BradReesWork** [comment]
rerun tests

**Review by VibhuJawa — APPROVED** [review]
LGTM, thanks for working on this Rick.   Will help debugging server crashes better for sure.

**Review by alexbarghi-nv — APPROVED** [review]
👍

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
