### PR TITLE
Format Python code with black

### PR DESCRIPTION
**Pull request by eriknw**
closes https://github.com/rapidsai/cugraph/issues/2527

I also added `.pre-commit-config.yaml` to make this easier to use and match versions (for example, I kept using a newer flake8 locally).  This uses the versions of black and flake8 that are in the `rapids` environment in the docker container.  There's a lot more we can do with pre-commit, but I didn't want to be overzealous in this PR.

_After_ this PR is merged, we should add a `.git-blame-ignore-revs` file so that I won't get blamed for everything :) .  See:
- https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html#avoiding-ruining-git-blame
- https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

Once this is merged, existing PRs should probably run `black` (version 22.3.0) on their branch before merging 22.12 branch into their branch.

**This changes the maximum line length to 88, which is the default for black**

### CODE REVIEW

**Comment by eriknw** [comment]
For sanity and convenience, this PR has a companion branch and PR https://github.com/rapidsai/cugraph/pull/2780 that has the necessary changes before running black.

https://github.com/rapidsai/cugraph/pull/2780 will be useful for keeping this branch up to date as PRs get merged, and for updating other PRs once this PR gets merge.

To verify the correctness of this PR, check out https://github.com/rapidsai/cugraph/pull/2780 and run `pre-commit run --all-files`.  The result should match this PR exactly.

**Comment by wence-** [comment]
FWIW, when this comes to merge, recommend squashing all the formatting commits and adding the final "change everything" commit hash to a top-level `.git-blame-ignore-revs` file. Then one can do `git config blame.ignoreRevsFile .git-blame-ignore-revs` and `git blame` will skip over this commit when assigning attribution to changed lines.

**Review by rlratzel — APPROVED** [review]
Assuming this contains the same changes as https://github.com/rapidsai/cugraph/pull/2780 + changes as the result of running `black`

**Comment by eriknw** [comment]
Test failure is from a timeout in a test.

**Comment by rlratzel** [comment]
rerun tests

reason: timeout failure while running a test that doesn't appear related to the PR changes, assuming it's a transient CI problem.

**Review by ajschmidt8 — APPROVED** [review]

**Comment by rlratzel** [comment]
@gpucibot merge

**Pull request merged**
