### PR TITLE
[FEA] Statically link all CUDA toolkit libraries

### PR DESCRIPTION
**Pull request by trxcllnt**
This PR ensures cuGraph statically links all the CUDA toolkit libraries (not just `cudart`) if a user enables `CUDA_STATIC_RUNTIME`.

### CODE REVIEW

**Review by BradReesWork — APPROVED** [review]

**Comment by trxcllnt** [comment]
@BradReesWork could you also take a look at https://github.com/rapidsai/cugraph-ops/pull/198? :pray:

**Review by ChuckHastings — APPROVED** [review]

**Comment by ChuckHastings** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
fix was subsumed in another PR

**Pull request closed without merging**
