### PR TITLE
Bug fixes for MNMG coarsen_graph, renumber_edgelist, relabel

### PR DESCRIPTION
**Pull request by seunghwak**
Bug fixes for MNMG coarsen_graph, renumber_edgelist, relabel

### CODE REVIEW

**Comment by seunghwak** [comment]
@ChuckHastings @rlratzel @aschaffer This affects you guys, so please take a look.

**Comment by seunghwak** [comment]
rerun tests.

**Comment by aschaffer** [comment]
> 
> 
> This affects you guys, so please take a look.

Unless you've changed the signatures of `sort_and_shuffle_values()` or `renumber_edgelist()` I (at least) should not be affected. It seems that you have not changed the signatures. Please correct me if I'm wrong, Thanks.

**Review by aschaffer — APPROVED** [review]

**Review by rlratzel — APPROVED** [review]

**Review by ChuckHastings — APPROVED** [review]

**Review by afender — APPROVED** [review]

**Comment by afender** [comment]
@gpucibot merge

**Pull request merged**
