### PR TITLE
Remove Pascal guard and test cuGraph use of cuco::static_map on Pascal

### PR DESCRIPTION
**Pull request by seunghwak**
Dependent on https://github.com/NVIDIA/cuCollections/pull/83

### CODE REVIEW

**Comment by ChuckHastings** [comment]
Looks like it's failing to build for `sm_60`.

**Comment by seunghwak** [comment]
> Looks like it's failing to build for `sm_60`.

Yeah... raft is pulling an older version of cuco.

After https://github.com/rapidsai/raft/pull/243 gets merged, need to update RAFT git tag as well.

**Comment by BradReesWork** [comment]
rerun tests

**Review by BradReesWork — APPROVED** [review]

**Review by ChuckHastings — APPROVED** [review]
Looks good once the raft PR merges

**Review by BradReesWork — APPROVED** [review]

**Comment by seunghwak** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Review by rlratzel — APPROVED** [review]

**Comment by seunghwak** [comment]
rerun tests

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
