### PR TITLE
Replace all references to CHECK_CUDA with RAFT_CHECK_CUDA

### PR DESCRIPTION
**Pull request by ChuckHastings**
RAFT is providing a separate implementation that we want to use.

### CODE REVIEW

**Review by cjnolet — APPROVED** [review]
LGTM. Haha, I guess I should have looked more closely at where you were using the macro and just made the change for you guys.

**Comment by seunghwak** [comment]
So, we're mostly using CUDA_TRY instead of CUDA_CHECK, and is there any reason we should keep both?

**Comment by seunghwak** [comment]
And maybe... shouldn't we better rename CUDA_TRY to either CUDA_CHECK or rename CUDA_TRY to RAFT_CUDA_TRY?

**Comment by ChuckHastings** [comment]
> And maybe... shouldn't we better rename either CUDA_TRY to CUDA_CHECK or rename CUDA_TRY to RAFT_CUDA_TRY?

I can change the CUDA_TRY references to RAFT_CUDA_CHECK if that's the preferred spelling :-)

I will make that change and push an update.

**Comment by seunghwak** [comment]
> 

I forgot the details, AFAIK, there was some discussion about CUDA_TRY and CUDA_CHECK in the past... I might be completely wrong, but I guess we were using CUDA_CHECK in the past, but we switched to CUDA_TRY when we decided to handle errors using exceptions. Let me dig into the history more.

**Comment by seunghwak** [comment]
@cjnolet @ChuckHastings 

So, in raft, we have both CUDA_TRY, CUDA_CHECK, and CHECK_CUDA (https://github.com/rapidsai/raft/blob/branch-22.02/cpp/include/raft/cudart_utils.h).

For CUBLAS, we have both CUBLAS_CHECK & CUBLAS_TRY. For NCCL, we have only NCCL_TRY. I haven't checked for other CUDA libraries but I guess the situation might be similar.

I guess all these exist due to some backward compatibility reasons, but I think we should first decide between _TRY and _CHECK first and better be consistent.

**Comment by BradReesWork** [comment]
rerun tests

**Review by BradReesWork — APPROVED** [review]

**Comment by cjnolet** [comment]
@seunghwak, I think in the end, `CUDA_CHECK` is just calling `CUDA_TRY` in RAFT. I'm okay w/ either name we choose, though I'm thinking we should consider also prefixing the macros for the other library wrappers w/ `RAFT_`. This will avoid future potential conflicts but will also allow us to directly make use of the RAFT logging once that's moved over.

**Comment by seunghwak** [comment]
> @seunghwak, I think in the end, `CUDA_CHECK` is just calling `CUDA_TRY` in RAFT. I'm okay w/ either name we choose, though I'm thinking we should consider also prefixing the macros for the other library wrappers w/ `RAFT_`. This will avoid future potential conflicts but will also allow us to directly make use of the RAFT logging once that's moved over.
> 
> Whichever names we choose, I'll also update RAFT and cuML to use them.

I'm also fine with either choice as long as consistent.

**Comment by cjnolet** [comment]
PR for renaming updates has been merged on the raft side. `RAFT_CUDA_TRY` should be used now when running any cuda functions and `RAFT_CHECK_CUDA` should be used with a stream to check errors (and sync in debug mode).

**Pull request closed without merging**
