### PR TITLE
MG WCC improvements

### PR DESCRIPTION
**Pull request by seunghwak**
Should be merged after PR #1636.

- Undo NCCL 2.9.6 bug workarounds.
- MG WCC weak scaling improvements.

### CODE REVIEW

**Review by aschaffer — APPROVED** [review]

**Comment by seunghwak** [comment]
rerun tests

**Comment by rlratzel** [comment]
rerun tests

**Review by ChuckHastings — APPROVED** [review]

**Comment by BradReesWork** [comment]
@gpucibot merge

**Comment by BradReesWork** [comment]
rerun tests

**Comment by seunghwak** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by BradReesWork** [comment]
Rerun tests

**Review by rlratzel — APPROVED** [review]
Warning: I'm approving my own py test update.

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
