### PR TITLE
Update to UCX-Py 0.24

### PR DESCRIPTION
**Pull request by pentschev**

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]

**Comment by pentschev** [comment]
It seems that all the pending builds are from November 22nd, the relevant ones are all green. Could we try merging this @BradReesWork @ajschmidt8 ?

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
Any check ending in `/` won't turn green here. They'll continue to say `Pending` since we can't delete statuses from commits. Those checks were due to a typo that we initially made when rolling out some changes. So as long as the other checks pass, this can be merged.

i.e. `gpuCI/cugraph/gpu/cuda/11.2/driver-495/python/3.8/ubuntu18.04/` won't pass, but `gpuCI/cugraph/gpu/cuda/11.2/driver-495/python/3.8/ubuntu18.04` should (the difference being the last `/` character).

**Comment by BradReesWork** [comment]
@ajschmidt8 thanks.

**Comment by BradReesWork** [comment]
@gpucibot merge

**Comment by rlratzel** [comment]
@gpucibot merge

**Review by rlratzel — APPROVED** [review]

**Pull request merged**
