### PR TITLE
[FIX] Update cugraph-PyG Dependencies to include cuGraph

### LINKED ISSUE #3494: cugraph-pyg needs to depend on cugraph in pyproject.toml
`cugraph-pyg` needs to explicitly add `cugraph` as a dependency.

This requires an edit to `dependencies.yaml` and rerunning the file generator (see comment in `pyproject.toml`)

### PR DESCRIPTION
**Pull request by alexbarghi-nv**
Closes #3494

### CODE REVIEW

**Review by tingyu66 — CHANGES_REQUESTED** [review]
Should we also add 
```diff
+  py_run_cugraph_pyg:
+    output: pyproject
+    pyproject_dir: python/cugraph-pyg
+    extras:
+      table: project
+    includes:
+      - python_run_cugraph_pyg
```
to `files` key and rerun `rapids-dependency-file-generator` to get `python/cugraph-pyg/pyproject.toml` updated as well?

In addition, as we are pushing cugraph-ops models into cugraph-pyg, do you think we should make `pylibcugraphops` a hard dependency of cugraph-pyg? Same applies to cugraph-dgl as well.

**Comment by alexbarghi-nv** [comment]
> Should we also add
> 
> ```diff
> +  py_run_cugraph_pyg:
> +    output: pyproject
> +    pyproject_dir: python/cugraph-pyg
> +    extras:
> +      table: project
> +    includes:
> +      - python_run_cugraph_pyg
> ```
> 
> to `files` key and rerun `rapids-dependency-file-generator` to get `python/cugraph-pyg/pyproject.toml` updated as well?
> 
> In addition, as we are pushing cugraph-ops models into cugraph-pyg, do you think we should make `pylibcugraphops` a hard dependency of cugraph-pyg? Same applies to cugraph-dgl as well.

I fixed the yaml and made sure the `pyproject.toml` got generated this time, sorry about that.

@VibhuJawa I think we should add the hard dependency on `pylibcugraphops` now that we actually have code that depends on it.  I'm going to add that to this PR as well if that's ok with you.

**Review by tingyu66 — APPROVED** [review]
LGTM

**Comment by VibhuJawa** [comment]
> > Should we also add
> > ```diff
> > +  py_run_cugraph_pyg:
> > +    output: pyproject
> > +    pyproject_dir: python/cugraph-pyg
> > +    extras:
> > +      table: project
> > +    includes:
> > +      - python_run_cugraph_pyg
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to `files` key and rerun `rapids-dependency-file-generator` to get `python/cugraph-pyg/pyproject.toml` updated as well?
> > In addition, as we are pushing cugraph-ops models into cugraph-pyg, do you think we should make `pylibcugraphops` a hard dependency of cugraph-pyg? Same applies to cugraph-dgl as well.
> 
> I fixed the yaml and made sure the `pyproject.toml` got generated this time, sorry about that.
> 
> @VibhuJawa I think we should add the hard dependency on `pylibcugraphops` now that we actually have code that depends on it. I'm going to add that to this PR as well if that's ok with you.

I think that is fine by me. It aligns well with our integration direction  moving forward.

**Comment by alexbarghi-nv** [comment]
Per discussion with @tingyu66 we are only going to add `pylibcugraphops` as a dependency for the conda package.  We can't make it a pip dependency since pip wheels aren't being build for `cugraph-ops` packages yet.

**Pull request merged**
