### PR TITLE
[REVIEW] BUG Update weights check in bc and graph prims wrappers

### PR DESCRIPTION
**Pull request by hlinsen**
This PR fixes the check for weights in betweenness_centrality and edge_betweenness_centrality wrappers.
Addresses issue https://github.com/rapidsai/cugraph/issues/1282.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Review by afender — CHANGES_REQUESTED** [review]
Thanks, @hlinsen. Could you elaborate on this fix in the context of my earlier comment: 
https://github.com/rapidsai/cugraph/issues/1282#issuecomment-734949024

In particular, I think we should throw an error when weights are passed since this is not supported.

**Review by BradReesWork — APPROVED** [review]

**Review by BradReesWork — CHANGES_REQUESTED** [review]
there should be an else condition after the weight checks

**Comment by hlinsen** [comment]
> Thanks, @hlinsen. Could you elaborate on this fix in the context of my earlier comment:
> [#1282 (comment)](https://github.com/rapidsai/cugraph/issues/1282#issuecomment-734949024)
> 
> In particular, I think we should throw an error when weights are passed since this is not supported.

The weights are currently throwing an error here: https://github.com/rapidsai/cugraph/blob/branch-0.17/python/cugraph/centrality/betweenness_centrality.py#L237. The ones inside the wrapper are used to construct the graph but are ignored during computation.

**Review by BradReesWork — APPROVED** [review]

**Review by afender — APPROVED** [review]
Thanks for adding the test and clarifying @hlinsen :+1:

**Comment by hlinsen** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by hlinsen** [comment]
rerun tests

**Comment by hlinsen** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by hlinsen** [comment]
rerun tests

**Pull request merged**
