### PR TITLE
[DO NOT MERGE] PR with prior cugraph/raft build to debug CentOS CI failure

### PR DESCRIPTION
**Pull request by dantegd**

### CODE REVIEW

**Comment by dantegd** [comment]
rerun tests

**Comment by dantegd** [comment]
rerun tests

**Comment by dantegd** [comment]
rerun tests

**Comment by ChuckHastings** [comment]
Thanks @dantegd for creating this so we could experiment.

RMM bug was corrected (https://github.com/rapidsai/rmm/pull/862) so we can close this.

**Pull request closed without merging**
