### PR TITLE
Remove `IncludeCategories` from `.clang-format`

### PR DESCRIPTION
**Pull request by codereport**
It was recently noticed that the `IncludeCategories`:
```
IncludeCategories:
  - Regex:           '^<ext/.*\.h>'
    Priority:        2
  - Regex:           '^<.*\.h>'
    Priority:        1
  - Regex:           '^<.*'
    Priority:        2
  - Regex:           '.*'
    Priority:        3
```
In the `.clang-format` are not really necessary as `ext` has no meaning in RAPIDS. This PR removes these.

Note these changes are being made in all repos:
* `cudf`: https://github.com/rapidsai/cudf/pull/9876
* `rmm`: https://github.com/rapidsai/rmm/pull/933
* `cuml`: https://github.com/rapidsai/cuml/pull/4438

### CODE REVIEW

**Review by ChuckHastings — APPROVED** [review]
Looks good once you fix the copyright error

**Comment by BradReesWork** [comment]
rerun tests

**Comment by codereport** [comment]
@BradReesWork @ChuckHastings can one of you merge? I don't have commit access. :pray:

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
