### PR TITLE
[FEA] Support Edge ID Lookup in PyLibcuGraph

### PR DESCRIPTION
**Pull request by alexbarghi-nv**
Support Edge ID lookup in `pylibcugraph`.  Also fixes some bugs in the C API (i.e. lookup table not being cleaned up correctly, container being incorrectly dereferenced as graph).

Verified in rapidsai/cugraph-gnn#50

### CODE REVIEW

**Review by ChuckHastings — APPROVED** [review]
Thanks for catching these!

**Review by seunghwak — APPROVED** [review]
LGTM

**Review by rlratzel — COMMENTED** [review]
The Python/Cython changes look fine, just a couple of questions/requests:
* Would it be better to be more explicit and replace the word "container" with "map", since (I'm assuming) it has to be a map?
* Can you add a smoketest of some kind for the PLC updates?  This would also be great for users looking for an example of how to use the new APIs.

**Comment by alexbarghi-nv** [comment]
> * Would it be better to be more explicit and replace the word "container" with "map", since (I'm assuming) it has to be a map?

We're calling it `EdgeIdLookupTable` at the Python level.  That should be ok, right?

**Review by rlratzel — APPROVED** [review]
Looks great, thanks @alexbarghi-nv !

**Pull request merged**
