### PR TITLE
 Forward Merge branch-24.06 into branch-24.08

### PR DESCRIPTION
**Pull request by nv-rliu**
Replaces #4433

### CODE REVIEW

**Comment by nv-rliu** [comment]
This PR should resolve the dependency error in the pip devcontainer build
https://github.com/rapidsai/raft/pull/2347

**Comment by jameslamb** [comment]
> *Once this PR is merged, it should resolve the dependency error in the pip devcontainer build and unblock CI.
https://github.com/rapidsai/raft/pull/2347*

@nv-rliu that's been replaced by this one: https://github.com/rapidsai/raft/pull/2349

**Comment by trxcllnt** [comment]
The base image for the `cuda-11.8-pip` and `cuda12.2-pip` devcontainers need to be updated to match these:
* https://github.com/rapidsai/cugraph/pull/4404/files#diff-24df28c8a2d558aaa21912c662c31e431dfd89760388d92bc0ca345f2772e0b1R8
* https://github.com/rapidsai/cugraph/pull/4404/files#diff-bf761d14216aac0c37c7a3447e060c92609b3d5873dd88c773cc681e31a8c89cR8

**Comment by rlratzel** [comment]
Added a DO NOT MERGE label to prevent accidental squash merging.
Ops, please remove the label when you're ready to properly merge.

**Pull request merged**
