### PR TITLE
[REVIEW] fix_column_rename

### PR DESCRIPTION
**Pull request by Iroy30**

### CODE REVIEW

**Comment by Iroy30** [comment]
rerun tests

**Comment by trxcllnt** [comment]
I also fixed this yesterday for myself, but didn't get to submit https://github.com/rapidsai/cugraph/pull/976 until just now.

One thing to note is `rename()` now defaults to `copy=True`, which we can probably avoid in cuGraph internals.

**Comment by Iroy30** [comment]
#976 addresses the renaming changes.

**Comment by afender** [comment]
Closing as duplicate of #976

**Pull request closed without merging**
