### PR TITLE
fix handling of fanout == -1

### LINKED ISSUE #2425: [FEA] Support getting all the neighboring edges for the uniform_neighbor_sample
**Describe the solution you'd like and any additional context**

For GNN workflows when running  on validation/test we need to sample all the neighboring edges .   I think we should support `uniform_neighbor_sample` to allow an option to return that.  

If we want to match DGL behavior we can probably return all neighbors for  `Fan-Out=-1` .  

See related DGL documentation [here](https://github.com/dmlc/dgl/blob/740cd7061067067535fc0caf8b262f5919330d12/python/dgl/sampling/neighbor.py#L40-L44)

Please note that currently below fails  with `CUGRAPH_UNKNOWN_ERROR` , we should probably raise an informative error as `-1` is the default value for DGL library and users may end up trying it on their own. 

 
```python

import cudf
import cugraph
import numpy as np

df = cudf.DataFrame({'source':[1,2,3,4],
                     'destination':[2,3,4,1]
                    })
df = df.astype(np.int32)
df['weight']=1.0

G = cugraph.Graph(directed=True)
G.from_cudf_edgelist(df,edge_attr='weight')

sample_df = cugraph.uniform_neighbor_sample(
    G,
    cudf.Series([1,2]),
    fanout_vals=[-1]
)
```
```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [6], in <cell line: 14>()
     11 G = cugraph.Graph(directed=True)
     12 G.from_cudf_edgelist(df,edge_attr='weight')
---> 14 sample_df = cugraph.uniform_neighbor_sample(
     15     G,
     16     cudf.Series([1,2]),
     17     fanout_vals=[-1]
     18 )

File ~/dgl/cugraph/python/cugraph/cugraph/sampling/uniform_neighbor_sample.py:113, in uniform_neighbor_sample(G, start_list, fanout_vals, with_replacement, is_edge_ids)
    107 do_expensive_check = False
    109 sg = SGGraph(resource_handle, graph_props, srcs, dsts, weights,
    110              store_transposed, renumber, do_expensive_check)
    112 sources, destinations, indices = \
--> 113     pylibcugraph_uniform_neighbor_sample(resource_handle, sg, start_list,
    114                                          fanout_vals, with_replacement,
    115                                          do_expensive_check)
    117 df = cudf.DataFrame()
    118 df["sources"] = sources

File pylibcugraph/uniform_neighbor_sample.pyx:142, in pylibcugraph.uniform_neighbor_sample.uniform_neighbor_sample()

File pylibcugraph/utils.pyx:51, in pylibcugraph.utils.assert_success()

RuntimeError: non-success value returned from cugraph_uniform_neighbor_sample: CUGRAPH_UNKNOWN_ERROR
```

### PR DESCRIPTION
**Pull request by ChuckHastings**
Uniform neighbor sampling isn't working properly with fanout specifying -1.

The `partially_decompress_edge_partition_to_fill_edgelist` function didn't handle SG properly.

closes #2425

### CODE REVIEW

**Comment by ChuckHastings** [comment]
rerun tests

**Comment by ChuckHastings** [comment]
rerun tests

**Comment by ChuckHastings** [comment]
rerun tests

**Comment by ChuckHastings** [comment]
rerun tests

**Review by seunghwak — APPROVED** [review]

**Comment by ChuckHastings** [comment]
@gpucibot merge

**Pull request merged**
