### PR TITLE
Updates for recent RAFT API changes

### PR DESCRIPTION
**Pull request by cjnolet**

### CODE REVIEW

**Review by BradReesWork — APPROVED** [review]

**Comment by seunghwak** [comment]
Not a complaint to this PR, but are we using `cpp/src/utilities/spmv_1D.cu` anywhere? Can't we just delete this? @ChuckHastings

**Review by seunghwak — APPROVED** [review]
Thanks!!!

**Comment by ChuckHastings** [comment]
> Not a complaint to this PR, but are we using `cpp/src/utilities/spmv_1D.cu` anywhere? Can't we just delete this? @ChuckHastings

Good point.  Will create a separate PR for that.

**Review by ChuckHastings — APPROVED** [review]

**Comment by cjnolet** [comment]
This went down a bad path on the raft side and I realized more changes were needed (including removing `using namespace` across the spectral header files). I'm closing this for #2067

**Pull request closed without merging**
