### PR TITLE
nx-cugraph: handle seed argument in edge_betweenness_centrality

### PR DESCRIPTION
**Pull request by eriknw**
CC @rlratzel who brought this to my attention and can test this fix

### CODE REVIEW

**Review by rlratzel — APPROVED** [review]
I tested this change and it passed.

**Comment by rlratzel** [comment]
Followup: do we know why our CI coverage didn't initially catch this?  I'm wondering if this PR should also have an updated test.

**Comment by eriknw** [comment]
A test would be nice... and it sounds like you have a case that exercises this ;) . Will your code be added to the repo at some point?

**Pull request merged**
