### PR TITLE
Also building cpp MG tests as part of conda/CI libcugraph builds

### PR DESCRIPTION
**Pull request by rlratzel**
Also building cpp MG tests as part of conda/CI libcugraph builds.

This addresses recent issues where commits were merged that broke MG test builds that were not caught in CI.

Tested locally using both a CentOS and Ubuntu `gpuCI` container to run the same build command in the recipe, but did not run the actual `conda build` command on the recipe.  This required additional system packages to be installed in the `gpuCI` containers:
CentOS:
```
yum install openmpi-devel
export PATH=/usr/lib64/openmpi/bin:$PATH
```
Ubuntu:
```
apt install libopenmpi-dev openmpi-bin
```

### CODE REVIEW

**Review by ChuckHastings — APPROVED** [review]
Looks good (assuming it passes CI :-) )

**Review by ajschmidt8 — APPROVED** [review]
Approved, but CI won't pass until the latest package installation changes are published. Should be done within an hour or two.

**Comment by rlratzel** [comment]
rerun tests

**Comment by rlratzel** [comment]
@gpucibot merge

**Comment by rlratzel** [comment]
@gpucibot merge

**Comment by rlratzel** [comment]
rerun tests

**Pull request merged**
