### PR TITLE
Updating a few headers that have been renamed in raft

### PR DESCRIPTION
**Pull request by cjnolet**

### CODE REVIEW

**Review by ChuckHastings — APPROVED** [review]
Can this be pointed back at RAFT 22.04 now?

Looks good otherwise.

**Comment by cjnolet** [comment]
@ChuckHastings assuming CI passes, it should be ready to merge

**Comment by cjnolet** [comment]
Not sure what could be causing this failure off the top of my head, but with my (somewhat limited) knowledge of CPM, I'm guessing from this [CI log](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cugraph/job/prb/job/cugraph-cpu-cuda-build-arm64/CUDA=11.5/614/display/redirect) it's possible that Thrust is being pulled in transitively from both `rmm` and `raft`, which is causing the target be defined twice? @robertmaynard is it possible this could be causing the issue here? I notice cugraph-ops is bringing in `rmm` [here](https://github.com/rapidsai/cugraph-ops/tree/branch-22.04/cmake/thirdparty) so maybe that's propagating to cugraph as a transitive dependency?

**Comment by robertmaynard** [comment]
rerun tests

**Comment by robertmaynard** [comment]
The failing CI should be fixed by https://github.com/rapidsai/raft/pull/532

**Comment by ChuckHastings** [comment]
rerun tests

**Comment by ChuckHastings** [comment]
rerun tests

**Comment by rlratzel** [comment]
Rerunning tests since #2095 has been merged which is needed by CI for this PR.

rerun tests

**Review by Ethyling — APPROVED** [review]

**Comment by cjnolet** [comment]
@ChuckHastings @rlratzel This is ready to be merged and is not dependent on any further changes in RAFT. Just to get this in quickly, I can also open a follow-on PR to remove the existing `git_helpers.py` in `ci/utils` if that would be helpful (I propose we keep the changes to the copyright checker script since they match cuml and raft).

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
