### PR TITLE
[REVIEW] Parquet read and concat within workers

### PR DESCRIPTION
**Pull request by afender**
Added 
- concat within workers: to be used instead of `reparation` for better perf and scalability
- MG Parquet pipeline test/example 

Needs #1145, skipping CI till it's merged.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Review by BradReesWork — APPROVED** [review]

**Comment by afender** [comment]
rerun tests

**Comment by afender** [comment]
@BradReesWork / @raydouglass do you know why CI is not running on this PR anymore?

**Review by Iroy30 — APPROVED** [review]
lgtm

**Comment by afender** [comment]
rerun tests

**Pull request merged**
