### PR TITLE
Fix optional and cstddef includes

### PR DESCRIPTION
**Pull request by gitbuda**

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Review by seunghwak — APPROVED** [review]
LGTM

**Comment by seunghwak** [comment]
This PR should target branch 22.02

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by ChuckHastings** [comment]
rerun tests

**Review by ChuckHastings — APPROVED** [review]

**Comment by BradReesWork** [comment]
@gpucibot merge

**Comment by ChuckHastings** [comment]
@gpucibot merge

**Pull request merged**
