### PR TITLE
[REVIEW] Replace gdf_dtype_from_value

### LINKED ISSUE #662: [BUG] gdf_dtype_from_value was replaced
The call gdf_dtype_from_value was replaced with gdf_dtype_from_dtype in  cuDF refactoring

### PR DESCRIPTION
**Pull request by BradReesWork**
closes #662

### CODE REVIEW

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by trxcllnt** [comment]
@bradreeswork if you hit merge on https://github.com/BradReesWork/cugraph/pull/1, it'll make its way into this PR and should resolve the rest of these failures

**Comment by BradReesWork** [comment]
> Can you also make updates to `ci/release/update-version.sh`? Doing so will automate these changes in the future. See [rapidsai/cudf#3724](https://github.com/rapidsai/cudf/pull/3724)

The update-version is working.  I was just trying to force the version changes to see if that was causing the issue

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Pull request merged**
