### PR TITLE
Add additional `kwargs` to GATConv 

### PR DESCRIPTION
**Pull request by tingyu66**
Support deterministic/high-precision flags in mha primitives, introduced in https://github.com/rapidsai/cugraph-ops/pull/607

### CODE REVIEW

**Review by stadlmax — APPROVED** [review]
LGTM

**Comment by stadlmax** [comment]
@tingyu66 Since we might run into gray areas of the benchmark by only passing kwargs, can you explicitly include all flags in the API?

**Review by alexbarghi-nv — APPROVED** [review]
👍

**Pull request merged**
