### PR TITLE
[REVIEW] Simple edge list generator

### PR DESCRIPTION
**Pull request by afender**
The implementation leverages single GPU calls and the example shows how to generate an arbitrary number of edge lists and write all the files to disk with csv or parquet writer (which can then be loaded on multiple GPUs with the corresponding dask cudf reader).
Rand values are generated with NumPy which was fast enough, later this part can be moved to the GPU. Currently, it takes just a minute or so to generate and write a dozen of GB to disk.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Review by BradReesWork — APPROVED** [review]

**Comment by afender** [comment]
rerun tests

**Comment by afender** [comment]
rerun tests

**Comment by afender** [comment]
rerun tests

**Pull request merged**
