### PR TITLE
[RELEASE] v0.6 cuGraph Release

### PR DESCRIPTION
**Pull request by mike-wendt**
### What does this mean?
Only hotfix and/or critical bug level issues should be merged into `branch-0.6` until release (merging of this PR).

### What is the purpose of this PR?
- Update documentation
- Allow testing for the new release
- Enable a means to merge `branch-0.6` into `master` for the release

### CODE REVIEW

**Comment by raydouglass** [comment]
rerun tests

**Comment by raydouglass** [comment]
rerun tests

**Comment by dillon-cullinan** [comment]
rerun tests

**Comment by raydouglass** [comment]
rerun tests

**Comment by raydouglass** [comment]
rerun tests

**Pull request merged**
