### PR TITLE
Update decompress_to_edgelist to handle edge types

### PR DESCRIPTION
**Pull request by naimnv**
Update decompress_to_edgelist to handle edge types

### CODE REVIEW

**Review by seunghwak — COMMENTED** [review]
LGTM but @jnke2016 needs a decompress_to_edgelist function that takes just a graph view object and an edge_property_device_view_t object of integer types (i.e. int32_t and int64_t for now, and in the future, we may need to support floating point types as well). Do you think it is better to implement this in this PR or address this in a separate PR?

**Comment by naimnv** [comment]
> LGTM but @jnke2016 needs a decompress_to_edgelist function that takes just a graph view object and an edge_property_device_view_t object of integer types (i.e. int32_t and int64_t for now, and in the future, we may need to support floating point types as well). Do you think it is better to implement this in this PR or address this in a separate PR?

He can just pass it instead of edge_id_view if edge_property_device_view_t object is of integer types (i.e. int32_t and int64_t 
or pass it instead of edge_weights_view if edge_property_device_view_t object is of floating point types. And he needs for triangle count tests, IIRC

**Comment by naimnv** [comment]
> > LGTM but @jnke2016 needs a decompress_to_edgelist function that takes just a graph view object and an edge_property_device_view_t object of integer types (i.e. int32_t and int64_t for now, and in the future, we may need to support floating point types as well). Do you think it is better to implement this in this PR or address this in a separate PR?
> 
> He can just pass it instead of edge_id_view if edge_property_device_view_t object is of integer types (i.e. int32_t and int64_t or pass it instead of edge_weights_view if edge_property_device_view_t object is of floating point types. And he needs for triangle count tests, IIRC

Otherwise we need an additional 72 explicit instantiations

**Comment by seunghwak** [comment]
> > LGTM but @jnke2016 needs a decompress_to_edgelist function that takes just a graph view object and an edge_property_device_view_t object of integer types (i.e. int32_t and int64_t for now, and in the future, we may need to support floating point types as well). Do you think it is better to implement this in this PR or address this in a separate PR?
> 
> He can just pass it instead of edge_id_view if edge_property_device_view_t object is of integer types (i.e. int32_t and int64_t or pass it instead of edge_weights_view if edge_property_device_view_t object is of floating point types. And he needs it for triangle count tests, IIRC.
> 
> Otherwise we need an additional 72 explicit instantiations and I can address it in a separate PR.

Yeah... let me think more about this... There is no guarantee that the integer type of the edge_property_device_view_t object and edge_id_t will coincide, and this solution sounds like a hack than a proper solution. But too many explicit instantiations are also problematic.

**Review by seunghwak — APPROVED** [review]

**Review by jnke2016 — APPROVED** [review]

**Review by ChuckHastings — APPROVED** [review]

**Pull request merged**
