### PR TITLE
[REVIEW] Fixed typo in README; Jaccard Similarity had a missing c

### PR DESCRIPTION
**Pull request by lushl9301**

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by lushl9301** [comment]
> Thanks for the update and could you also update the change log?
> 
> https://github.com/rapidsai/cugraph/blob/branch-0.15/CHANGELOG.md
> 
> cuGraph 0.15.0 (Date TBD) Bug Fixes part.

hi! I thought I was a tiny typo fix so didn't want to mess up the change log. Do I need to do it now? I see this has already been merged.

Thanks :)

**Comment by seunghwak** [comment]
No need to, CHNAGE log needs to be updated to start the CI, but Brad has a right to merge without passing the CI. Thank you very much for the contribution!!!

**Comment by lushl9301** [comment]
Thank you for your time and the explanation. :)

**Pull request merged**
