### PR TITLE
Add coverage for uniform neighbor sampling

### LINKED ISSUE #2620: [FEA] Add coverage for SG PLC Uniform Neighbor Sampling
**Describe the solution you'd like and any additional context**
There is no coverage for SG PLC `uniform neighborhood sampling`. In fact, the tests in-place are for the MG implementation though skipped because they are not yet supported.

### PR DESCRIPTION
**Pull request by jnke2016**
This PR adds coverage for SG PLC uniform neighborhood sampling

closes #2620

### CODE REVIEW

**Comment by jnke2016** [comment]
rerun tests

**Review by rlratzel — APPROVED** [review]

**Comment by jnke2016** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
Removing `ops-codeowners` from the required reviews since it doesn't seem there are any file changes that we're responsible for. Feel free to add us back if necessary.

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
