### PR TITLE
[REVIEW] Support Pandas 1.0+

### PR DESCRIPTION
**Pull request by brandon-b-miller**
Small change to fix a few cuGraph tests when Pandas 1.0+ is used.

xref https://github.com/rapidsai/cudf/pull/4546

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by seunghwak** [comment]
Need to update change log to start tests.

**Comment by brandon-b-miller** [comment]
rerun tests

**Comment by afender** [comment]
Duplicate of #976

**Pull request closed without merging**
