### PR TITLE
Enabling pytest code coverage output by default

### PR DESCRIPTION
**Pull request by jnke2016**
added the coverage plugin option by default
added pytest-cov package

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]

**Review by BradReesWork — APPROVED** [review]

**Comment by BradReesWork** [comment]
@gpucibot merge

**Comment by BradReesWork** [comment]
rerun tests

**Comment by rlratzel** [comment]
rerun tests

**Comment by BradReesWork** [comment]
@gpucibot merge

**Pull request merged**
