### PR TITLE
[REVIEW] Use cudf pandas version

### PR DESCRIPTION
**Pull request by trxcllnt**
cuDF recently upgraded to Pandas 0.25 in https://github.com/rapidsai/cudf/pull/3486

### CODE REVIEW

**Comment by trxcllnt** [comment]
@raydouglass removing the dependency entirely is what we've done in similar PRs (https://github.com/rapidsai/cugraph/pull/463, https://github.com/rapidsai/cugraph/pull/562) before. I'm not a conda dependency resolution expert, but I think this was @kkraus14's recommended solution.

**Comment by afender** [comment]
rerun tests

**Comment by jakirkham** [comment]
> @jakirkham Is there a convention here? What's your opinion?

The convention would be to make it explicit.

That said, given how tightly integrated all RAPIDS libraries releases are, it's probably possible to rely on how cuDF is constraining the version (as you suggest), @raydouglass.

**Comment by BradReesWork** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Comment by trxcllnt** [comment]
rerun tests

**Comment by BradReesWork** [comment]
rerun tests

**Pull request merged**
