### PR TITLE
[REVIEW] Update `cuda-python` dependency to 11.7.1

### PR DESCRIPTION
**Pull request by galipremsagar**
This PR is a mirror of https://github.com/rapidsai/cugraph/pull/2848/ to unblock `22.12` CI

### CODE REVIEW

**Comment by ChuckHastings** [comment]
`conda_build.sh` needs an update to the copyright year

**Review by ChuckHastings — APPROVED** [review]

**Review by ajschmidt8 — APPROVED** [review]

**Comment by galipremsagar** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Comment by ChuckHastings** [comment]
@gpucibot merge

**Pull request merged**
